// server.js
require('dotenv').config();
const express    = require('express');
const cors       = require('cors');
const crypto     = require('crypto');
const { exec }   = require('child_process');
const fs         = require('fs');
const path       = require('path');
const os         = require('os');
const db         = require('./db');
const { validateCFG }       = require('./utils/cfgValidator');
const { recommendExercise } = require('./utils/cosineSimilarity');
const { CARTClassifier }    = require('./utils/cartModel');

// ─── Load CART model at startup ───────────────────────────────────
// The model file is generated by running: node utils/trainCart.js
// Falls back gracefully if the file is missing (first-run scenario).
const CART_MODEL_PATH = path.join(__dirname, 'utils', 'cart_model.json');
const cartModel = new CARTClassifier();
let cartReady = false;

try {
  if (fs.existsSync(CART_MODEL_PATH)) {
    const exported = JSON.parse(fs.readFileSync(CART_MODEL_PATH, 'utf8'));
    cartModel.importTree(exported);
    cartReady = true;
    console.log(`✅ CART model loaded from ${CART_MODEL_PATH}`);
    console.log(`   Trained at : ${exported.meta.trained_at}`);
  } else {
    console.warn(`⚠ CART model not found at ${CART_MODEL_PATH}.`);
    console.warn(`  Run: node utils/trainCart.js   to generate it.`);
    console.warn(`  Falling back to heuristic rules until model is available.`);
  }
} catch (err) {
  console.error(`❌ Failed to load CART model: ${err.message}`);
  console.warn(`  Falling back to heuristic rules.`);
}

const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));

/* ─────────────────────────────────────
   HELPER — SHA-256 password hash
───────────────────────────────────── */
function hashPassword(password) {
  return crypto.createHash('sha256').update(password + 'codapt_salt').digest('hex');
}

/* ─────────────────────────────────────
   HELPER — map CART level → problem_tier
   CART outputs: 'Easy' | 'Intermediate' | 'Hard'
   problem_tier in DB: 'Beginner' | 'Intermediate' | 'Advanced'
───────────────────────────────────── */
function cartLevelToTier(cartLevel) {
  const map = {
    Easy:         'Beginner',
    Intermediate: 'Intermediate',
    Hard:         'Advanced',
  };
  return map[cartLevel] || 'Beginner';
}

function shouldDemote(profile, isCorrect, attempts, hintUsed, hasHardEvidence) {
  if (hasHardEvidence) return false;
  const struggled    = !isCorrect || hintUsed || attempts >= 3;
  const weakProfile  = profile.success_rate < 0.50;
  return struggled && weakProfile;
}

function shouldDemoteToEasy(profile, attempts, structuralErrors) {
  return (
    attempts >= 4 &&
    profile.success_rate < 0.40 &&
    structuralErrors > 1
  );
}

/* ══════════════════════════════════════
   CODE EXECUTION — /api/run
══════════════════════════════════════ */
app.post('/api/run', async (req, res) => {
  const { language, code } = req.body;
  if (!code || !language)
    return res.status(400).json({ output: 'No code or language provided.', error: true });

  const tmpDir = os.tmpdir();
  const lang   = language.toLowerCase();

  try {
    if (lang === 'python') {
      const filePath = path.join(tmpDir, `codapt_${Date.now()}.py`);
      fs.writeFileSync(filePath, code, 'utf8');
      runProcess(`python "${filePath}"`, filePath, res);

    } else if (lang === 'javascript') {
      const filePath = path.join(tmpDir, `codapt_${Date.now()}.js`);
      fs.writeFileSync(filePath, code, 'utf8');
      runProcess(`node "${filePath}"`, filePath, res);

    } else if (lang === 'java') {
      const wrapped  = wrapJava(code);
      const filePath = path.join(tmpDir, 'Main.java');
      fs.writeFileSync(filePath, wrapped, 'utf8');

      exec(`javac "${filePath}"`, { timeout: 10000 }, (compileErr, _, compileStderr) => {
        if (compileErr) {
          cleanup(filePath);
          return res.json({ output: compileStderr || 'Compilation error.', error: true });
        }
        const classPath = tmpDir;
        exec(`java -cp "${classPath}" Main`, { timeout: 10000 }, (runErr, stdout, stderr) => {
          cleanup(filePath);
          cleanup(path.join(tmpDir, 'Main.class'));
          if (runErr && !stdout)
            return res.json({ output: stderr || runErr.message, error: true });
          res.json({ output: stdout.trimEnd(), error: false });
        });
      });

    } else {
      res.status(400).json({ output: `Unsupported language: ${language}`, error: true });
    }
  } catch (err) {
    res.status(500).json({ output: err.message, error: true });
  }
});

function runProcess(command, filePath, res) {
  exec(command, { timeout: 10000 }, (err, stdout, stderr) => {
    cleanup(filePath);
    if (err && !stdout) return res.json({ output: stderr || err.message, error: true });
    res.json({ output: stdout.trimEnd(), error: !!stderr });
  });
}

function cleanup(filePath) {
  try { fs.unlinkSync(filePath); } catch (_) {}
}

function wrapJava(code) {
  if (/\bclass\s+\w+/.test(code))
    return code.replace(/public\s+class\s+\w+/, 'public class Main');
  return `public class Main {
    public static void main(String[] args) {
${code.split('\n').map(l => '        ' + l).join('\n')}
    }
}`;
}

/* ══════════════════════════════════════
   AUTH ROUTES
══════════════════════════════════════ */
app.post('/api/auth/register', async (req, res) => {
  try {
    const { name, username, email, password, photo } = req.body;
    if (!email || !password)
      return res.status(400).json({ error: 'Email and password are required.' });

    // SUPABASE (pg): use { rows } and $1 placeholders
    const { rows: existing } = await db.query(
      'SELECT id FROM users WHERE email = $1',
      [email]
    );
    if (existing.length > 0)
      return res.status(409).json({ error: 'An account with this email already exists.' });

    const hashed          = hashPassword(password);
    const displayName     = name     || email.split('@')[0];
    const displayUsername = username || email.split('@')[0];

    // SUPABASE (pg): use RETURNING id to get the inserted row's id
    const { rows: result } = await db.query(
      `INSERT INTO users (name, username, email, password_hash, photo)
       VALUES ($1, $2, $3, $4, $5) RETURNING id`,
      [displayName, displayUsername, email, hashed, photo || null]
    );

    res.status(201).json({
      success: true,
      user: {
        id:       result[0].id,
        name:     displayName,
        username: displayUsername,
        email,
        photo:    photo || null
      }
    });
  } catch (err) {
    console.error('❌ REGISTER:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password)
      return res.status(400).json({ error: 'Email and password are required.' });

    const hashed = hashPassword(password);

    // SUPABASE (pg): { rows } and $1, $2
    const { rows } = await db.query(
      `SELECT id, name, username, email, photo
       FROM users WHERE email = $1 AND password_hash = $2`,
      [email, hashed]
    );

    if (rows.length === 0)
      return res.status(401).json({ error: 'Invalid email or password.' });

    const user = rows[0];
    res.json({
      success: true,
      user: {
        id:       user.id,
        name:     user.name,
        username: user.username,
        email:    user.email,
        photo:    user.photo || null
      }
    });
  } catch (err) {
    console.error('❌ LOGIN:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/auth/google', async (req, res) => {
  try {
    const { name, email, photo } = req.body;
    if (!email) return res.status(400).json({ error: 'Google did not return an email.' });

    // SUPABASE (pg): { rows } and $1
    const { rows: existing } = await db.query(
      `SELECT id, name, username, email, photo FROM users WHERE email = $1`,
      [email]
    );

    if (existing.length > 0) {
      const user = existing[0];
      if (photo && photo !== user.photo) {
        await db.query('UPDATE users SET photo = $1 WHERE id = $2', [photo, user.id]);
        user.photo = photo;
      }
      return res.json({
        success: true,
        user: {
          id:       user.id,
          name:     user.name,
          username: user.username,
          email:    user.email,
          photo:    user.photo || null
        }
      });
    }

    const username = email.split('@')[0];

    // SUPABASE (pg): RETURNING to get new id
    const { rows: result } = await db.query(
      `INSERT INTO users (name, username, email, password_hash, photo)
       VALUES ($1, $2, $3, 'google-oauth', $4) RETURNING id`,
      [name || username, username, email, photo || null]
    );

    res.status(201).json({
      success: true,
      user: {
        id:       result[0].id,
        name:     name || username,
        username,
        email,
        photo:    photo || null
      }
    });
  } catch (err) {
    console.error('❌ GOOGLE AUTH:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.put('/api/auth/profile/:userId', async (req, res) => {
  try {
    const { userId } = req.params;
    const { name, username, email, password, photo } = req.body;
    const fields = [];
    const values = [];
    let   idx    = 1; // SUPABASE (pg): numbered placeholders start at $1

    if (name)                { fields.push(`name = $${idx++}`);          values.push(name); }
    if (username)            { fields.push(`username = $${idx++}`);      values.push(username); }
    if (email)               { fields.push(`email = $${idx++}`);         values.push(email); }
    if (photo !== undefined) { fields.push(`photo = $${idx++}`);         values.push(photo); }
    if (password && password !== '••••••••') {
      fields.push(`password_hash = $${idx++}`);
      values.push(hashPassword(password));
    }

    if (fields.length === 0) return res.status(400).json({ error: 'No fields to update.' });

    values.push(userId); // last param = userId
    await db.query(
      `UPDATE users SET ${fields.join(', ')} WHERE id = $${idx}`,
      values
    );

    // SUPABASE (pg): { rows } and $1
    const { rows } = await db.query(
      'SELECT id, name, username, email, photo FROM users WHERE id = $1',
      [userId]
    );
    res.json({ success: true, user: rows[0] });
  } catch (err) {
    console.error('❌ UPDATE PROFILE:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — GET PROBLEMS
══════════════════════════════════════ */
app.get('/api/problems/:language/:concept/:difficulty', async (req, res) => {
  try {
    const { language, concept, difficulty } = req.params;
    const tier = req.query.tier || 'Beginner';

    // SUPABASE (pg): { rows } and $1–$4
    const { rows } = await db.query(
      `SELECT * FROM problems
       WHERE language = $1 AND concept = $2 AND difficulty = $3 AND problem_tier = $4
       ORDER BY id ASC`,
      [language, concept, difficulty, tier]
    );
    res.json(rows);
  } catch (err) {
    console.error('❌ GET PROBLEMS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — SUBMIT CODE
══════════════════════════════════════ */
app.post('/api/submit', async (req, res) => {
  try {
    const {
      userId, problemId, language, concept,
      code, attempts, timeSpent, isCorrect, hintUsed = false
    } = req.body;

    // ── 1. Fetch problem meta ────────────────────────────────────
    // SUPABASE (pg): { rows } and $1
    const { rows: problemRows } = await db.query(
      'SELECT * FROM problems WHERE id = $1',
      [problemId]
    );
    const problem           = problemRows[0] || {};
    const requiredConstruct = problem.required_construct || null;
    const expectedOutput    = problem.expected_output    || '';

    // ── 2. CFG validation ────────────────────────────────────────
    const cfgResult        = validateCFG(code, language, requiredConstruct, expectedOutput);
    const syntaxErrors     = cfgResult.syntaxErrors;
    const structuralErrors = cfgResult.structuralErrors;
    const cfgFeedback      = cfgResult.feedback;
    const constructUsed    = cfgResult.constructUsed;

    // ── 3. Final correctness ─────────────────────────────────────
    const finalCorrect = isCorrect && constructUsed;
    const successValue = finalCorrect ? 1 : 0;

    // ── 4. Save submission ───────────────────────────────────────
    // SUPABASE (pg): $1–$11
    await db.query(
      `INSERT INTO submissions
       (user_id, problem_id, language, concept, submitted_code,
        attempts, time_spent, is_correct,
        syntax_errors, structural_errors, hint_used)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
      [
        userId,
        problemId,
        language,
        concept,
        code,
        attempts,
        timeSpent,
        finalCorrect,
        syntaxErrors,
        structuralErrors,
        hintUsed ? true : false  // pg uses true/false booleans (not 1/0)
      ]
    );

    // ── 5. Upsert user_profiles ──────────────────────────────────
    // SUPABASE (pg): { rows } and $1–$3
    const { rows: existing } = await db.query(
      `SELECT * FROM user_profiles WHERE user_id = $1 AND language = $2 AND concept = $3`,
      [userId, language, concept]
    );

    // Fetch real total task count
    // SUPABASE (pg): COUNT(*) returns a string in pg — cast to int
    const { rows: problemCountRows } = await db.query(
      `SELECT COUNT(*) AS total FROM problems WHERE language = $1 AND concept = $2 AND difficulty = $3`,
      [language, concept, problem.difficulty || 'Easy']
    );
    const totalTasksInDB = parseInt(problemCountRows[0]?.total, 10) || 3;

    if (existing.length === 0) {
      // SUPABASE (pg): $1–$10
      await db.query(
        `INSERT INTO user_profiles
         (user_id, language, concept, total_attempts, tasks_completed,
          total_tasks, success_rate, avg_time_spent, avg_attempts,
          syntax_errors, structural_errors, performance_level)
         VALUES ($1, $2, $3, 1, $4, $5, $6, $7, 1, $8, $9, 'Easy')`,
        [
          userId, language, concept,
          successValue, totalTasksInDB, successValue, timeSpent,
          syntaxErrors, structuralErrors
        ]
      );
    } else {
      // SUPABASE (pg): $1–$9
      await db.query(
        `UPDATE user_profiles SET
           total_attempts    = total_attempts + 1,
           tasks_completed   = tasks_completed + $1,
           total_tasks       = $2,
           success_rate      = (success_rate * total_attempts + $3) / (total_attempts + 1),
           avg_time_spent    = (avg_time_spent * total_attempts + $4) / (total_attempts + 1),
           avg_attempts      = (avg_attempts  * total_attempts + 1) / (total_attempts + 1),
           syntax_errors     = syntax_errors + $5,
           structural_errors = structural_errors + $6
         WHERE user_id = $7 AND language = $8 AND concept = $9`,
        [
          successValue, totalTasksInDB, successValue, timeSpent,
          syntaxErrors, structuralErrors,
          userId, language, concept
        ]
      );
    }

    // ── 6. CART classification ───────────────────────────────────
    // SUPABASE (pg): { rows } and $1–$3
    const { rows: profileRows } = await db.query(
      `SELECT success_rate, avg_time_spent, avg_attempts,
              syntax_errors, structural_errors, performance_level
       FROM user_profiles WHERE user_id = $1 AND language = $2 AND concept = $3`,
      [userId, language, concept]
    );

    const profile = profileRows[0] ?? {
      success_rate:      successValue,
      avg_time_spent:    timeSpent,
      avg_attempts:      attempts,
      syntax_errors:     syntaxErrors,
      structural_errors: structuralErrors,
      performance_level: 'Easy'
    };

    // SUPABASE (pg): { rows } and $1–$3
    // pg returns COUNT as string — parse to int for comparison
    const { rows: hardSolveRows } = await db.query(
      `SELECT COUNT(*) AS count
       FROM submissions s
       JOIN problems p ON s.problem_id = p.id
       WHERE s.user_id = $1
         AND p.language = $2
         AND p.concept = $3
         AND p.problem_tier = 'Advanced'
         AND s.is_correct = true
         AND s.attempts <= 2
         AND s.hint_used = false`,
      [userId, language, concept]
    );
    const hasHardEvidence = parseInt(hardSolveRows[0].count, 10) > 0;

    // ── CART ML classification ────────────────────────────────────
    const featureVector = {
      success_rate:      profile.success_rate      ?? 0,
      avg_attempts:      profile.avg_attempts      ?? attempts,
      avg_time_spent:    profile.avg_time_spent     ?? timeSpent,
      syntax_errors:     profile.syntax_errors      ?? syntaxErrors,
      structural_errors: profile.structural_errors  ?? structuralErrors,
    };

    let level;
    if (cartReady) {
      level = cartModel.predict(featureVector);
      console.log(`🌳 CART predicted level="${level}" for user=${userId} concept=${concept}`);
    } else {
      if (
        featureVector.success_rate      >= 0.80 &&
        featureVector.avg_attempts      <= 2    &&
        featureVector.syntax_errors     <= 1    &&
        featureVector.structural_errors <= 1
      ) {
        level = 'Hard';
      } else if (featureVector.success_rate >= 0.50) {
        level = 'Intermediate';
      } else {
        level = 'Easy';
      }
      console.log(`⚠ CART fallback heuristic level="${level}" (model not loaded)`);
    }

    if (userId) {
      // SUPABASE (pg): $1–$4
      await db.query(
        `UPDATE user_profiles SET performance_level = $1
         WHERE user_id = $2 AND language = $3 AND concept = $4`,
        [level, userId, language, concept]
      );
    }

    let nextTier   = cartLevelToTier(level);
    let tierReason = null;

    if (nextTier === 'Advanced' && shouldDemote(profile, finalCorrect, attempts, hintUsed, hasHardEvidence)) {
      nextTier   = 'Intermediate';
      tierReason = 'We are giving you an Intermediate exercise to strengthen this concept before continuing with Advanced problems.';
    }

    if (nextTier === 'Intermediate' && shouldDemoteToEasy(profile, attempts, structuralErrors)) {
      nextTier   = 'Beginner';
      tierReason = 'We are revisiting the fundamentals of this concept to build a stronger foundation.';
    }

    // ── 7. Update daily_progress ─────────────────────────────────
    const today = new Date().toISOString().slice(0, 10);
    const score = Math.round(profile.success_rate * 100);
    if (userId) {
      // SUPABASE (pg): ON CONFLICT replaces MySQL's ON DUPLICATE KEY UPDATE
      // Requires a UNIQUE constraint on (user_id, language, progress_date) in your schema
      await db.query(
        `INSERT INTO daily_progress (user_id, language, progress_date, score)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT (user_id, language, progress_date) DO UPDATE SET score = $5`,
        [userId, language, today, score, score]
      );
    }

    // ── 8. Cosine similarity recommendation ──────────────────────
    const updatedProfile = { ...profile, performance_level: level };

    // SUPABASE (pg): { rows } and $1
    const { rows: allProblems } = await db.query(
      `SELECT * FROM problems WHERE language = $1`,
      [language]
    );

    const { problem: recommended, similarityScore, explanation } =
      recommendExercise(updatedProfile, problem, allProblems);

    // ── 9. Save to recommendations table ─────────────────────────
    if (recommended && userId) {
      // SUPABASE (pg): { rows } and $1–$2
      const { rows: existingRec } = await db.query(
        `SELECT id FROM recommendations WHERE user_id = $1 AND source_problem_id = $2`,
        [userId, problemId]
      );

      if (existingRec.length === 0) {
        // SUPABASE (pg): NOW() works in both MySQL and PostgreSQL
        await db.query(
          `INSERT INTO recommendations
           (user_id, source_problem_id, recommended_problem_id,
            similarity_score, explanation, created_at)
           VALUES ($1, $2, $3, $4, $5, NOW())`,
          [userId, problemId, recommended.id, similarityScore, explanation]
        );
      } else {
        // SUPABASE (pg): $1–$5
        await db.query(
          `UPDATE recommendations SET
             recommended_problem_id = $1,
             similarity_score       = $2,
             explanation            = $3,
             created_at             = NOW()
           WHERE user_id = $4 AND source_problem_id = $5`,
          [recommended.id, similarityScore, explanation, userId, problemId]
        );
      }
    }

    // ── 10. Return full result ────────────────────────────────────
    // Check mastery: all tasks solved with ≥60% success
    const { rows: masterCheck } = await db.query(
      `SELECT tasks_completed, total_tasks, success_rate
       FROM user_profiles WHERE user_id = $1 AND language = $2 AND concept = $3`,
      [userId, language, concept]
    );
    const mr         = masterCheck[0];
    const isMastered = mr
      ? mr.tasks_completed >= mr.total_tasks && (mr.success_rate * 100) >= 60
      : false;

    res.json({
      success:         true,
      level,
      nextTier,
      correct:         finalCorrect,
      syntaxErrors,
      structuralErrors,
      cfgFeedback,
      constructUsed,
      isMastered,
      recommendation: recommended
        ? {
            id:              recommended.id,
            title:           recommended.title,
            concept:         recommended.concept,
            difficulty:      recommended.difficulty,
            problem_tier:    recommended.problem_tier,
            language:        recommended.language,
            similarityScore,
            explanation
          }
        : null
    });

  } catch (err) {
    console.error('❌ SUBMIT:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — GET RECOMMENDATIONS for a user
══════════════════════════════════════ */
app.get('/api/recommendations/:userId', async (req, res) => {
  try {
    const { userId } = req.params;

    // SUPABASE (pg): { rows } and $1
    const { rows } = await db.query(
      `SELECT
         r.id,
         r.similarity_score,
         r.explanation,
         r.created_at,
         sp.title        AS source_title,
         sp.concept      AS source_concept,
         sp.difficulty   AS source_difficulty,
         sp.problem_tier AS source_tier,
         rp.id           AS rec_problem_id,
         rp.title        AS rec_title,
         rp.concept      AS rec_concept,
         rp.difficulty   AS rec_difficulty,
         rp.problem_tier AS rec_tier,
         rp.language     AS rec_language,
         rp.instruction  AS rec_instruction
       FROM recommendations r
       JOIN problems sp ON r.source_problem_id      = sp.id
       JOIN problems rp ON r.recommended_problem_id = rp.id
       WHERE r.user_id = $1
       ORDER BY r.created_at DESC
       LIMIT 10`,
      [userId]
    );

    res.json(rows);
  } catch (err) {
    console.error('❌ GET RECOMMENDATIONS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — GET PROGRESS (for ProfilePage)
══════════════════════════════════════ */
app.get('/api/progress/:userId', async (req, res) => {
  try {
    const { userId } = req.params;

    // SUPABASE (pg): { rows } and $1
    const { rows } = await db.query(
      `SELECT language, concept, tasks_completed, total_tasks,
              success_rate, performance_level, syntax_errors, structural_errors
       FROM user_profiles WHERE user_id = $1`,
      [userId]
    );

    const progress = {};
    rows.forEach(row => {
      if (!progress[row.language]) progress[row.language] = {};
      const tasksCompleted = row.tasks_completed;
      const totalTasks     = row.total_tasks;
      const successRate    = Math.round(row.success_rate * 100);
      progress[row.language][row.concept] = {
        tasksCompleted,
        totalTasks,
        successRate,
        performanceLevel: row.performance_level,
        syntaxErrors:     row.syntax_errors,
        structuralErrors: row.structural_errors,
        mastered:         tasksCompleted >= totalTasks && successRate >= 60,
      };
    });
    res.json(progress);
  } catch (err) {
    console.error('❌ GET PROGRESS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/admin/users', async (req, res) => {
  try {
    const { rows } = await db.query(
      `SELECT
         u.id,
         u.name,
         u.username,
         u.email,
         u.photo,
         COALESCE(SUM(up.tasks_completed), 0) AS tasks_completed,
         COALESCE(SUM(up.total_tasks), 0) AS total_tasks,
         CASE WHEN COALESCE(SUM(up.total_tasks), 0) > 0
           THEN ROUND(SUM(up.tasks_completed)::numeric / SUM(up.total_tasks) * 100)
           ELSE 0 END AS progress,
         COALESCE(COUNT(DISTINCT up.concept), 0) AS concepts_count,
         COALESCE(MAX(dp.progress_date)::text, '') AS last_active
       FROM users u
       LEFT JOIN user_profiles up ON up.user_id = u.id
       LEFT JOIN daily_progress dp ON dp.user_id = u.id
       GROUP BY u.id
       ORDER BY u.name ASC`
    );

    const users = rows.map(row => ({
      id: row.id,
      name: row.name,
      username: row.username,
      email: row.email,
      photo: row.photo || null,
      progress: Number(row.progress),
      completedLessons: Number(row.tasks_completed),
      certificates: Number(row.concepts_count),
      lastActive: row.last_active || 'Unknown',
      isBanned: false,
      scores: {
        python: 0,
        javascript: 0,
        java: 0
      }
    }));

    res.json(users);
  } catch (err) {
    console.error('❌ GET ADMIN USERS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — GET DAILY PROGRESS
══════════════════════════════════════ */
app.get('/api/daily-progress/:userId', async (req, res) => {
  try {
    const { userId } = req.params;

    // SUPABASE (pg): DATE_SUB(CURDATE(), INTERVAL 14 DAY) →
    //                CURRENT_DATE - INTERVAL '14 days'
    const { rows } = await db.query(
      `SELECT progress_date, language, score
       FROM daily_progress
       WHERE user_id = $1
         AND progress_date >= CURRENT_DATE - INTERVAL '14 days'
       ORDER BY progress_date ASC, language ASC`,
      [userId]
    );

    res.json(rows);
  } catch (err) {
    console.error('❌ GET DAILY PROGRESS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — RETRAIN CART MODEL
   POST /api/retrain
══════════════════════════════════════ */
app.post('/api/retrain', async (req, res) => {
  const scriptPath = path.join(__dirname, 'utils', 'trainCart.js');

  if (!fs.existsSync(scriptPath)) {
    return res.status(500).json({ error: `Training script not found at ${scriptPath}` });
  }

  exec(`node "${scriptPath}"`, { timeout: 60000 }, (err, stdout, stderr) => {
    if (err) {
      console.error('❌ Retrain failed:', stderr || err.message);
      return res.status(500).json({ error: 'Training failed', details: stderr || err.message });
    }

    try {
      const exported = JSON.parse(fs.readFileSync(CART_MODEL_PATH, 'utf8'));
      cartModel.importTree(exported);
      cartReady = true;
      console.log('✅ CART model reloaded after retraining.');
      res.json({
        success:    true,
        trained_at: exported.meta.trained_at,
        features:   exported.meta.features,
        max_depth:  exported.meta.max_depth,
        output:     stdout,
      });
    } catch (loadErr) {
      res.status(500).json({ error: 'Model trained but failed to reload', details: loadErr.message });
    }
  });
});

/* ══════════════════════════════════════
   API — INSPECT CART MODEL
   GET /api/cart-model
══════════════════════════════════════ */
app.get('/api/cart-model', (req, res) => {
  if (!cartReady) {
    return res.status(503).json({
      ready:   false,
      message: 'CART model not loaded. Run: node utils/trainCart.js',
    });
  }
  res.json({ ready: true, ...cartModel.exportTree() });
});

/* ══════════════════════════════════════
   API — CONNECTION TEST
══════════════════════════════════════ */
app.get('/api/test', async (req, res) => {
  try {
    // SUPABASE (pg): { rows } — COUNT(*) returns string, cast to int
    const { rows } = await db.query('SELECT COUNT(*) AS total FROM problems');
    res.json({ status: 'connected', problems: parseInt(rows[0].total, 10) });
  } catch (err) {
    res.status(500).json({ status: 'error', message: err.message });
  }
});

/* ══════════════════════════════════════
   ADMIN PROFILE — SAVE
   PUT /api/admin/profile
══════════════════════════════════════ */
app.put('/api/admin/profile', async (req, res) => {
  try {
    const { name, username, email } = req.body;
    
    if (!name || !username || !email) {
      return res.status(400).json({ error: 'Name, username, and email are required.' });
    }

    // For this simple admin profile, we'll store in a settings table
    // First, check if admin profile exists
    const { rows: existing } = await db.query(
      'SELECT * FROM admin_settings WHERE admin_id = 1'
    );

    if (existing.length > 0) {
      // Update existing
      const { rows } = await db.query(
        'UPDATE admin_settings SET name = $1, username = $2, email = $3, updated_at = NOW() WHERE admin_id = 1 RETURNING *',
        [name, username, email]
      );
      res.json({ success: true, admin: rows[0] });
    } else {
      // Create new
      const { rows } = await db.query(
        'INSERT INTO admin_settings (admin_id, name, username, email, created_at, updated_at) VALUES (1, $1, $2, $3, NOW(), NOW()) RETURNING *',
        [name, username, email]
      );
      res.json({ success: true, admin: rows[0] });
    }
  } catch (err) {
    console.error('❌ SAVE ADMIN PROFILE:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   ADMIN PROFILE — GET
   GET /api/admin/profile
══════════════════════════════════════ */
app.get('/api/admin/profile', async (req, res) => {
  try {
    const { rows } = await db.query(
      'SELECT * FROM admin_settings WHERE admin_id = 1'
    );
    if (rows.length === 0) {
      return res.json({ admin: { name: 'Admin', username: 'admin', email: '' } });
    }
    res.json({ admin: rows[0] });
  } catch (err) {
    console.error('❌ GET ADMIN PROFILE:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   START SERVER
══════════════════════════════════════ */
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Backend running at http://localhost:${PORT}`));