// server.js
require('dotenv').config();
const express    = require('express');
const cors       = require('cors');
const crypto     = require('crypto');
const { exec }   = require('child_process');
const fs         = require('fs');
const path       = require('path');
const os         = require('os');
const db         = require('./db');
const { validateCFG }       = require('./utils/cfgValidator');
const { recommendExercise } = require('./utils/cosineSimilarity');
const { CARTClassifier }    = require('./utils/cartModel');

// ─── Load CART model at startup ───────────────────────────────────
// The model file is generated by running: node utils/trainCart.js
// Falls back gracefully if the file is missing (first-run scenario).
const CART_MODEL_PATH = path.join(__dirname, 'utils', 'cart_model.json');
const cartModel = new CARTClassifier();
let cartReady = false;

try {
  if (fs.existsSync(CART_MODEL_PATH)) {
    const exported = JSON.parse(fs.readFileSync(CART_MODEL_PATH, 'utf8'));
    cartModel.importTree(exported);
    cartReady = true;
    console.log(`✅ CART model loaded from ${CART_MODEL_PATH}`);
    console.log(`   Trained at : ${exported.meta.trained_at}`);
  } else {
    console.warn(`⚠ CART model not found at ${CART_MODEL_PATH}.`);
    console.warn(`  Run: node utils/trainCart.js   to generate it.`);
    console.warn(`  Falling back to heuristic rules until model is available.`);
  }
} catch (err) {
  console.error(`❌ Failed to load CART model: ${err.message}`);
  console.warn(`  Falling back to heuristic rules.`);
}

const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));

/* ─────────────────────────────────────
   HELPER — SHA-256 password hash
───────────────────────────────────── */
function hashPassword(password) {
  return crypto.createHash('sha256').update(password + 'codapt_salt').digest('hex');
}

/* ─────────────────────────────────────
   HELPER — map CART level → problem_tier
   CART outputs: 'Easy' | 'Intermediate' | 'Hard'
   problem_tier in DB: 'Beginner' | 'Intermediate' | 'Advanced'
───────────────────────────────────── */
function cartLevelToTier(cartLevel) {
  const map = {
    Easy:         'Beginner',
    Intermediate: 'Intermediate',
    Hard:         'Advanced',
  };
  return map[cartLevel] || 'Beginner';
}


function shouldDemote(
  profile,
  isCorrect,
  attempts,
  hintUsed,
  hasHardEvidence
) {
  if (hasHardEvidence) return false;

  const struggled =
    !isCorrect ||
    hintUsed ||
    attempts >= 3;

  const weakProfile =
    profile.success_rate < 0.50;

  return struggled && weakProfile;
}

function shouldDemoteToEasy(
  profile,
  attempts,
  structuralErrors
) {
  return (
    attempts >= 4 &&
    profile.success_rate < 0.40 &&
    structuralErrors > 1
  );
}

/* ══════════════════════════════════════
   CODE EXECUTION — /api/run
══════════════════════════════════════ */
app.post('/api/run', async (req, res) => {
  const { language, code } = req.body;
  if (!code || !language)
    return res.status(400).json({ output: 'No code or language provided.', error: true });

  const tmpDir = os.tmpdir();
  const lang   = language.toLowerCase();

  try {
    if (lang === 'python') {
      const filePath = path.join(tmpDir, `codapt_${Date.now()}.py`);
      fs.writeFileSync(filePath, code, 'utf8');
      runProcess(`python "${filePath}"`, filePath, res);

    } else if (lang === 'javascript') {
      const filePath = path.join(tmpDir, `codapt_${Date.now()}.js`);
      fs.writeFileSync(filePath, code, 'utf8');
      runProcess(`node "${filePath}"`, filePath, res);

    } else if (lang === 'java') {
      const wrapped  = wrapJava(code);
      const filePath = path.join(tmpDir, 'Main.java');
      fs.writeFileSync(filePath, wrapped, 'utf8');

      exec(`javac "${filePath}"`, { timeout: 10000 }, (compileErr, _, compileStderr) => {
        if (compileErr) {
          cleanup(filePath);
          return res.json({ output: compileStderr || 'Compilation error.', error: true });
        }
        const classPath = tmpDir;
        exec(`java -cp "${classPath}" Main`, { timeout: 10000 }, (runErr, stdout, stderr) => {
          cleanup(filePath);
          cleanup(path.join(tmpDir, 'Main.class'));
          if (runErr && !stdout)
            return res.json({ output: stderr || runErr.message, error: true });
          res.json({ output: stdout.trimEnd(), error: false });
        });
      });

    } else {
      res.status(400).json({ output: `Unsupported language: ${language}`, error: true });
    }
  } catch (err) {
    res.status(500).json({ output: err.message, error: true });
  }
});

function runProcess(command, filePath, res) {
  exec(command, { timeout: 10000 }, (err, stdout, stderr) => {
    cleanup(filePath);
    if (err && !stdout) return res.json({ output: stderr || err.message, error: true });
    res.json({ output: stdout.trimEnd(), error: !!stderr });
  });
}

function cleanup(filePath) {
  try { fs.unlinkSync(filePath); } catch (_) {}
}

function wrapJava(code) {
  if (/\bclass\s+\w+/.test(code))
    return code.replace(/public\s+class\s+\w+/, 'public class Main');
  return `public class Main {
    public static void main(String[] args) {
${code.split('\n').map(l => '        ' + l).join('\n')}
    }
}`;
}

/* ══════════════════════════════════════
   AUTH ROUTES
══════════════════════════════════════ */
app.post('/api/auth/register', async (req, res) => {
  try {
    const { name, username, email, password, photo } = req.body;
    if (!email || !password)
      return res.status(400).json({ error: 'Email and password are required.' });

    const [existing] = await db.query('SELECT id FROM users WHERE email = ?', [email]);
    if (existing.length > 0)
      return res.status(409).json({ error: 'An account with this email already exists.' });

    const hashed          = hashPassword(password);
    const displayName     = name     || email.split('@')[0];
    const displayUsername = username || email.split('@')[0];

    const [result] = await db.query(
      `INSERT INTO users (name, username, email, password_hash, photo) VALUES (?, ?, ?, ?, ?)`,
      [displayName, displayUsername, email, hashed, photo || null]
    );

    res.status(201).json({
      success: true,
      user: { id: result.insertId, name: displayName, username: displayUsername, email, photo: photo || null }
    });
  } catch (err) {
    console.error('❌ REGISTER:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password)
      return res.status(400).json({ error: 'Email and password are required.' });

    const hashed = hashPassword(password);
    const [rows] = await db.query(
      `SELECT id, name, username, email, photo FROM users WHERE email = ? AND password_hash = ?`,
      [email, hashed]
    );

    if (rows.length === 0)
      return res.status(401).json({ error: 'Invalid email or password.' });

    const user = rows[0];
    res.json({ success: true, user: { id: user.id, name: user.name, username: user.username, email: user.email, photo: user.photo || null } });
  } catch (err) {
    console.error('❌ LOGIN:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/auth/google', async (req, res) => {
  try {
    const { name, email, photo } = req.body;
    if (!email) return res.status(400).json({ error: 'Google did not return an email.' });

    const [existing] = await db.query(
      `SELECT id, name, username, email, photo FROM users WHERE email = ?`, [email]
    );

    if (existing.length > 0) {
      const user = existing[0];
      if (photo && photo !== user.photo) {
        await db.query('UPDATE users SET photo = ? WHERE id = ?', [photo, user.id]);
        user.photo = photo;
      }
      return res.json({ success: true, user: { id: user.id, name: user.name, username: user.username, email: user.email, photo: user.photo || null } });
    }

    const username = email.split('@')[0];
    const [result] = await db.query(
      `INSERT INTO users (name, username, email, password_hash, photo) VALUES (?, ?, ?, 'google-oauth', ?)`,
      [name || username, username, email, photo || null]
    );
    res.status(201).json({ success: true, user: { id: result.insertId, name: name || username, username, email, photo: photo || null } });
  } catch (err) {
    console.error('❌ GOOGLE AUTH:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.put('/api/auth/profile/:userId', async (req, res) => {
  try {
    const { userId } = req.params;
    const { name, username, email, password, photo } = req.body;
    const fields = [], values = [];

    if (name)                { fields.push('name = ?');         values.push(name); }
    if (username)            { fields.push('username = ?');     values.push(username); }
    if (email)               { fields.push('email = ?');        values.push(email); }
    if (photo !== undefined) { fields.push('photo = ?');        values.push(photo); }
    if (password && password !== '••••••••') {
      fields.push('password_hash = ?');
      values.push(hashPassword(password));
    }

    if (fields.length === 0) return res.status(400).json({ error: 'No fields to update.' });

    values.push(userId);
    await db.query(`UPDATE users SET ${fields.join(', ')} WHERE id = ?`, values);

    const [rows] = await db.query(
      'SELECT id, name, username, email, photo FROM users WHERE id = ?', [userId]
    );
    res.json({ success: true, user: rows[0] });
  } catch (err) {
    console.error('❌ UPDATE PROFILE:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — GET PROBLEMS
   
   CHANGE 1: Now fetches by problem_tier instead of difficulty.
   
   The frontend (CodeEditor) sends:
     language  = Python / Java / JavaScript
     concept   = Variables / Loops / etc.
     difficulty = Easy / Intermediate / Hard  (concept group — unchanged)
   
   The server now uses difficulty to filter concept group AND
   problem_tier to filter internal difficulty (Beginner by default).
   
   The adaptive tier is passed as a query param: ?tier=Beginner
   If no tier is sent, defaults to Beginner so first load always works.
══════════════════════════════════════ */
app.get('/api/problems/:language/:concept/:difficulty', async (req, res) => {
  try {
    const { language, concept, difficulty } = req.params;

    // tier comes from query string — ?tier=Beginner / Intermediate / Advanced
    // Default to Beginner so the first load always works without changes to CodeEditor
    const tier = req.query.tier || 'Beginner';

    const [rows] = await db.query(
      `SELECT * FROM problems
       WHERE language = ? AND concept = ? AND difficulty = ? AND problem_tier = ?
       ORDER BY id ASC`,
      [language, concept, difficulty, tier]
    );
    res.json(rows);
  } catch (err) {
    console.error('❌ GET PROBLEMS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════════════════════════════════
   API — SUBMIT CODE
   
   CHANGE 2: After CART classifies the user's level, the server
   now also returns the recommended next problem_tier so the
   frontend knows which tier to fetch next.
══════════════════════════════════════════════════════════════════ */
app.post('/api/submit', async (req, res) => {
  try {
    const {
      userId, problemId, language, concept,
      code, attempts, timeSpent, isCorrect, hintUsed = false
    } = req.body;

    // ── 1. Fetch problem meta ────────────────────────────────────
    const [problemRows] = await db.query(
      'SELECT * FROM problems WHERE id = ?',
      [problemId]
    );
    const problem           = problemRows[0] || {};
    const requiredConstruct = problem.required_construct || null;
    const expectedOutput    = problem.expected_output    || '';

    // ── 2. CFG validation ────────────────────────────────────────
    const cfgResult        = validateCFG(code, language, requiredConstruct, expectedOutput);
    const syntaxErrors     = cfgResult.syntaxErrors;
    const structuralErrors = cfgResult.structuralErrors;
    const cfgFeedback      = cfgResult.feedback;
    const constructUsed    = cfgResult.constructUsed;

    // ── 3. Final correctness ─────────────────────────────────────
    const finalCorrect = isCorrect && constructUsed;
    const successValue = finalCorrect ? 1 : 0;

    // ── 4. Save submission ───────────────────────────────────────
    await db.query(
      `INSERT INTO submissions
      (user_id, problem_id, language, concept, submitted_code,
        attempts, time_spent, is_correct,
        syntax_errors, structural_errors, hint_used)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        userId,
        problemId,
        language,
        concept,
        code,
        attempts,
        timeSpent,
        finalCorrect,
        syntaxErrors,
        structuralErrors,
        hintUsed ? 1 : 0
      ]
    );

    // ── 5. Upsert user_profiles ──────────────────────────────────
    const [existing] = await db.query(
      `SELECT * FROM user_profiles WHERE user_id = ? AND language = ? AND concept = ?`,
      [userId, language, concept]
    );

    // Fetch real total task count from all tiers for this language/concept/difficulty
    const [problemCountRows] = await db.query(
      `SELECT COUNT(*) AS total FROM problems WHERE language = ? AND concept = ? AND difficulty = ?`,
      [language, concept, problem.difficulty || 'Easy']
    );
    const totalTasksInDB = problemCountRows[0]?.total || 3;

    if (existing.length === 0) {
      await db.query(
        `INSERT INTO user_profiles
         (user_id, language, concept, total_attempts, tasks_completed,
          total_tasks, success_rate, avg_time_spent, avg_attempts,
          syntax_errors, structural_errors, performance_level)
         VALUES (?, ?, ?, 1, ?, ?, ?, ?, 1, ?, ?, 'Easy')`,
        [userId, language, concept,
         successValue, totalTasksInDB, successValue, timeSpent,
         syntaxErrors, structuralErrors]
      );
    } else {
      await db.query(
        `UPDATE user_profiles SET
           total_attempts    = total_attempts + 1,
           tasks_completed   = tasks_completed + ?,
           total_tasks       = ?,
           success_rate      = (success_rate * total_attempts + ?) / (total_attempts + 1),
           avg_time_spent    = (avg_time_spent * total_attempts + ?) / (total_attempts + 1),
           avg_attempts      = (avg_attempts  * total_attempts + 1) / (total_attempts + 1),
           syntax_errors     = syntax_errors + ?,
           structural_errors = structural_errors + ?
         WHERE user_id = ? AND language = ? AND concept = ?`,
        [successValue, totalTasksInDB, successValue, timeSpent,
         syntaxErrors, structuralErrors,
         userId, language, concept]
      );
    }

    // ── 6. CART classification ───────────────────────────────────
    const [profileRows] = await db.query(
      `SELECT success_rate, avg_time_spent, avg_attempts,
              syntax_errors, structural_errors, performance_level
       FROM user_profiles WHERE user_id = ? AND language = ? AND concept = ?`,
      [userId, language, concept]
    );

    const profile = profileRows[0] ?? {
      success_rate:      successValue,
      avg_time_spent:    timeSpent,
      avg_attempts:      attempts,
      syntax_errors:     syntaxErrors,
      structural_errors: structuralErrors,
      performance_level: 'Easy'
    };


    const [hardSolves] = await db.query(
      `SELECT COUNT(*) AS count
      FROM submissions s
      JOIN problems p
        ON s.problem_id = p.id
      WHERE s.user_id = ?
        AND p.language = ?
        AND p.concept = ?
        AND p.problem_tier = 'Advanced'
        AND s.is_correct = 1
        AND s.attempts <= 2
        AND s.hint_used = 0
      `,
      [userId, language, concept]
    );

    const hasHardEvidence =
    hardSolves[0].count > 0;

    
    // ── CART ML classification ────────────────────────────────────
    // Build the feature vector from the current profile snapshot.
    // These are the exact same five features the model was trained on.
    const featureVector = {
      success_rate:      profile.success_rate      ?? 0,
      avg_attempts:      profile.avg_attempts      ?? attempts,
      avg_time_spent:    profile.avg_time_spent     ?? timeSpent,
      syntax_errors:     profile.syntax_errors      ?? syntaxErrors,
      structural_errors: profile.structural_errors  ?? structuralErrors,
    };

    // Use trained CART when available; fall back to heuristic rules
    // if trainCart.js has not been run yet (e.g. fresh install).
    let level;
    if (cartReady) {
      level = cartModel.predict(featureVector);
      console.log(`🌳 CART predicted level="${level}" for user=${userId} concept=${concept}`);
    } else {
      // Heuristic fallback (identical to previous behaviour — keeps the
      // server working on day 1 before trainCart.js is run)
      if (
        featureVector.success_rate      >= 0.80 &&
        featureVector.avg_attempts      <= 2    &&
        featureVector.syntax_errors     <= 1    &&
        featureVector.structural_errors <= 1
      ) {
        level = 'Hard';
      } else if (featureVector.success_rate >= 0.50) {
        level = 'Intermediate';
      } else {
        level = 'Easy';
      }
      console.log(`⚠ CART fallback heuristic level="${level}" (model not loaded)`);
    }

    if (userId) {
      await db.query(
        `UPDATE user_profiles SET performance_level = ?
         WHERE user_id = ? AND language = ? AND concept = ?`,
        [level, userId, language, concept]
      );
    }

    // CHANGE 2: Convert CART level to problem_tier for the frontend
    // This tells CodeEditor which tier to fetch next
    let nextTier = cartLevelToTier(level);

    let tierReason = null;

    if (
      nextTier === 'Advanced' &&
      shouldDemote(
        profile,
        finalCorrect,
        attempts,
        hintUsed,
        hasHardEvidence
      )
    ) {
      nextTier = 'Intermediate';

      tierReason =
        'We are giving you an Intermediate exercise to strengthen this concept before continuing with Advanced problems.';
    }

    if (
      nextTier === 'Intermediate' &&
      shouldDemoteToEasy(
        profile,
        attempts,
        structuralErrors
      )
    ) {
      nextTier = 'Beginner';

      tierReason =
        'We are revisiting the fundamentals of this concept to build a stronger foundation.';
    }
    // ── 7. Update daily_progress ─────────────────────────────────
    const today = new Date().toISOString().slice(0, 10);
    const score = Math.round(profile.success_rate * 100);
    if (userId) {
      await db.query(
        `INSERT INTO daily_progress (user_id, language, progress_date, score)
         VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE score = ?`,
        [userId, language, today, score, score]
      );
    }

    // ── 8. Cosine similarity recommendation ──────────────────────
    const updatedProfile = { ...profile, performance_level: level };

    const [allProblems] = await db.query(
      `SELECT * FROM problems WHERE language = ?`,
      [language]
    );

    const { problem: recommended, similarityScore, explanation } =
      recommendExercise(updatedProfile, problem, allProblems);

    // ── 9. Save to recommendations table ─────────────────────────
    if (recommended && userId) {
      const [existingRec] = await db.query(
        `SELECT id FROM recommendations
         WHERE user_id = ? AND source_problem_id = ?`,
        [userId, problemId]
      );

      if (existingRec.length === 0) {
        await db.query(
          `INSERT INTO recommendations
           (user_id, source_problem_id, recommended_problem_id,
            similarity_score, explanation, created_at)
           VALUES (?, ?, ?, ?, ?, NOW())`,
          [userId, problemId, recommended.id, similarityScore, explanation]
        );
      } else {
        await db.query(
          `UPDATE recommendations SET
             recommended_problem_id = ?,
             similarity_score       = ?,
             explanation            = ?,
             created_at             = NOW()
           WHERE user_id = ? AND source_problem_id = ?`,
          [recommended.id, similarityScore, explanation, userId, problemId]
        );
      }
    }

    // ── 10. Return full result ────────────────────────────────────
    res.json({
      success:          true,
      level,                  // 'Easy' | 'Intermediate' | 'Hard'  (CART output)
      nextTier,               // 'Beginner' | 'Intermediate' | 'Advanced'  (NEW — for frontend fetch)
      correct:          finalCorrect,
      syntaxErrors,
      structuralErrors,
      cfgFeedback,
      constructUsed,
      recommendation: recommended
        ? {
            id:              recommended.id,
            title:           recommended.title,
            concept:         recommended.concept,
            difficulty:      recommended.difficulty,
            problem_tier:    recommended.problem_tier,   // NEW — included in recommendation
            language:        recommended.language,
            similarityScore,
            explanation
          }
        : null
    });

  } catch (err) {
    console.error('❌ SUBMIT:', err.message);
    res.status(500).json({ error: err.message });
  }
});


/* ══════════════════════════════════════
   API — GET RECOMMENDATIONS for a user
══════════════════════════════════════ */
app.get('/api/recommendations/:userId', async (req, res) => {
  try {
    const { userId } = req.params;

    const [rows] = await db.query(
      `SELECT
         r.id,
         r.similarity_score,
         r.explanation,
         r.created_at,
         sp.title        AS source_title,
         sp.concept      AS source_concept,
         sp.difficulty   AS source_difficulty,
         sp.problem_tier AS source_tier,
         rp.id           AS rec_problem_id,
         rp.title        AS rec_title,
         rp.concept      AS rec_concept,
         rp.difficulty   AS rec_difficulty,
         rp.problem_tier AS rec_tier,
         rp.language     AS rec_language,
         rp.instruction  AS rec_instruction
       FROM recommendations r
       JOIN problems sp ON r.source_problem_id      = sp.id
       JOIN problems rp ON r.recommended_problem_id = rp.id
       WHERE r.user_id = ?
       ORDER BY r.created_at DESC
       LIMIT 10`,
      [userId]
    );

    res.json(rows);
  } catch (err) {
    console.error('❌ GET RECOMMENDATIONS:', err.message);
    res.status(500).json({ error: err.message });
  }
});


/* ══════════════════════════════════════
   API — GET PROGRESS (for ProfilePage)
══════════════════════════════════════ */
app.get('/api/progress/:userId', async (req, res) => {
  try {
    const { userId } = req.params;
    const [rows] = await db.query(
      `SELECT language, concept, tasks_completed, total_tasks,
              success_rate, performance_level, syntax_errors, structural_errors
       FROM user_profiles WHERE user_id = ?`,
      [userId]
    );

    const progress = {};
    rows.forEach(row => {
      if (!progress[row.language]) progress[row.language] = {};
      progress[row.language][row.concept] = {
        tasksCompleted:   row.tasks_completed,
        totalTasks:       row.total_tasks,
        successRate:      Math.round(row.success_rate * 100),
        performanceLevel: row.performance_level,
        syntaxErrors:     row.syntax_errors,
        structuralErrors: row.structural_errors
      };
    });
    res.json(progress);
  } catch (err) {
    console.error('❌ GET PROGRESS:', err.message);
    res.status(500).json({ error: err.message });
  }
});


app.get('/api/daily-progress/:userId', async (req, res) => {
  try {
    const { userId } = req.params;

    const [rows] = await db.query(
      `SELECT progress_date, language, score
       FROM daily_progress
       WHERE user_id = ?
         AND progress_date >= DATE_SUB(CURDATE(), INTERVAL 14 DAY)
       ORDER BY progress_date ASC, language ASC`,
      [userId]
    );

    res.json(rows);
  } catch (err) {
    console.error('❌ GET DAILY PROGRESS:', err.message);
    res.status(500).json({ error: err.message });
  }
});


/* ══════════════════════════════════════
   API — RETRAIN CART MODEL
   POST /api/retrain
   Triggers trainCart.js as a child process.
   Returns the new model's tree summary.
══════════════════════════════════════ */
app.post('/api/retrain', async (req, res) => {
  const scriptPath = path.join(__dirname, 'utils', 'trainCart.js');

  if (!fs.existsSync(scriptPath)) {
    return res.status(500).json({ error: `Training script not found at ${scriptPath}` });
  }

  exec(`node "${scriptPath}"`, { timeout: 60000 }, (err, stdout, stderr) => {
    if (err) {
      console.error('❌ Retrain failed:', stderr || err.message);
      return res.status(500).json({ error: 'Training failed', details: stderr || err.message });
    }

    // Reload the newly written model
    try {
      const exported = JSON.parse(fs.readFileSync(CART_MODEL_PATH, 'utf8'));
      cartModel.importTree(exported);
      cartReady = true;
      console.log('✅ CART model reloaded after retraining.');
      res.json({
        success:    true,
        trained_at: exported.meta.trained_at,
        features:   exported.meta.features,
        max_depth:  exported.meta.max_depth,
        output:     stdout,
      });
    } catch (loadErr) {
      res.status(500).json({ error: 'Model trained but failed to reload', details: loadErr.message });
    }
  });
});

/* ══════════════════════════════════════
   API — INSPECT CART MODEL
   GET /api/cart-model
   Returns the loaded tree structure and metadata.
══════════════════════════════════════ */
app.get('/api/cart-model', (req, res) => {
  if (!cartReady) {
    return res.status(503).json({
      ready: false,
      message: 'CART model not loaded. Run: node utils/trainCart.js',
    });
  }
  res.json({ ready: true, ...cartModel.exportTree() });
});

/* ══════════════════════════════════════
   API — CONNECTION TEST
══════════════════════════════════════ */
app.get('/api/test', async (req, res) => {
  try {
    const [rows] = await db.query('SELECT COUNT(*) AS total FROM problems');
    res.json({ status: 'connected', problems: rows[0].total });
  } catch (err) {
    res.status(500).json({ status: 'error', message: err.message });
  }
});


/* ══════════════════════════════════════
   START SERVER
══════════════════════════════════════ */
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Backend running at http://localhost:${PORT}`));