// server.js
require('dotenv').config();
const express    = require('express');
const cors       = require('cors');
const crypto     = require('crypto');
const { exec }   = require('child_process');
const fs         = require('fs');
const path       = require('path');
const os         = require('os');
const db         = require('./db');
const { validateCFG }       = require('./utils/cfgValidator');
const { recommendExercise } = require('./utils/cosineSimilarity');
const { CARTClassifier }    = require('./utils/cartModel');
const { getFallbackProblems, resolveProblemMetadata } = require('./utils/problemCatalog');
const { startInteractiveSession, writeToInteractiveSession, getInteractiveSessionOutput, removeInteractiveSession } = require('./utils/runCode');

// ─── Load CART model at startup ───────────────────────────────────
// The model file is generated by running: node utils/trainCart.js
// Falls back gracefully if the file is missing (first-run scenario).
const CART_MODEL_PATH = path.join(__dirname, 'utils', 'cart_model.json');
const cartModel = new CARTClassifier();
let cartReady = false;

try {
  if (fs.existsSync(CART_MODEL_PATH)) {
    const exported = JSON.parse(fs.readFileSync(CART_MODEL_PATH, 'utf8'));
    cartModel.importTree(exported);
    cartReady = true;
    console.log(`✅ CART model loaded from ${CART_MODEL_PATH}`);
    console.log(`   Trained at : ${exported.meta.trained_at}`);
  } else {
    console.warn(`⚠ CART model not found at ${CART_MODEL_PATH}.`);
    console.warn(`  Run: node utils/trainCart.js   to generate it.`);
    console.warn(`  Falling back to heuristic rules until model is available.`);
  }
} catch (err) {
  console.error(`❌ Failed to load CART model: ${err.message}`);
  console.warn(`  Falling back to heuristic rules.`);
}

const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));

async function ensureArchivedColumn() {
  try {
    await db.query(
      `ALTER TABLE problems
       ADD COLUMN IF NOT EXISTS archived BOOLEAN NOT NULL DEFAULT FALSE`
    );
    console.log('✅ ensured problems.archived column exists');
  } catch (err) {
    console.error('❌ Failed to ensure problems.archived column:', err.message);
  }
}

ensureArchivedColumn();

/* ─────────────────────────────────────
   HELPER — SHA-256 password hash
───────────────────────────────────── */
function hashPassword(password) {
  return crypto.createHash('sha256').update(password + 'codapt_salt').digest('hex');
}

/* ─────────────────────────────────────
   HELPER — map CART level → problem_tier
   CART outputs: 'Easy' | 'Intermediate' | 'Hard'
   problem_tier in DB: 'Beginner' | 'Intermediate' | 'Advanced'
───────────────────────────────────── */
function cartLevelToTier(cartLevel) {
  const map = {
    Easy:         'Beginner',
    Intermediate: 'Intermediate',
    Hard:         'Advanced',
  };
  return map[cartLevel] || 'Beginner';
}

function shouldDemote(profile, isCorrect, attempts, hintUsed, hasHardEvidence) {
  if (hasHardEvidence) return false;
  const struggled    = !isCorrect || hintUsed || attempts >= 3;
  const weakProfile  = profile.success_rate < 0.50;
  return struggled && weakProfile;
}

function shouldDemoteToEasy(profile, attempts, structuralErrors) {
  return (
    attempts >= 4 &&
    profile.success_rate < 0.40 &&
    structuralErrors > 1
  );
}

/* ══════════════════════════════════════
   CODE EXECUTION — /api/run
══════════════════════════════════════ */
app.post('/api/run', async (req, res) => {
  const { language, code, input = '', sessionId = null } = req.body;
  if (!code || !language)
    return res.status(400).json({ output: 'No code or language provided.', error: true });

  try {
    if (sessionId) {
      const result = writeToInteractiveSession(sessionId, input);
      return res.json({ output: result.output, error: result.error, sessionId, status: result.status });
    }

    const session = await startInteractiveSession({ language, code });
    return res.json({ output: session.output, error: false, sessionId: session.sessionId, status: session.status });
  } catch (err) {
    res.status(500).json({ output: err.message, error: true });
  }
});

app.post('/api/terminal/input', async (req, res) => {
  const { sessionId, input } = req.body;
  if (!sessionId) return res.status(400).json({ error: true, message: 'Missing sessionId' });
  const result = writeToInteractiveSession(sessionId, input);
  res.json(result);
});

app.get('/api/terminal/:sessionId', async (req, res) => {
  const { sessionId } = req.params;
  const result = getInteractiveSessionOutput(sessionId);
  res.json(result);
});

app.delete('/api/terminal/:sessionId', async (req, res) => {
  const { sessionId } = req.params;
  removeInteractiveSession(sessionId);
  res.json({ success: true });
});

function runProcess(command, filePath, res) {
  exec(command, { timeout: 10000 }, (err, stdout, stderr) => {
    cleanup(filePath);
    if (err && !stdout) return res.json({ output: stderr || err.message, error: true });
    res.json({ output: stdout.trimEnd(), error: !!stderr });
  });
}

function cleanup(filePath) {
  try { fs.unlinkSync(filePath); } catch (_) {}
}

function wrapJava(code) {
  if (/\bclass\s+\w+/.test(code))
    return code.replace(/public\s+class\s+\w+/, 'public class Main');
  return `public class Main {
    public static void main(String[] args) {
${code.split('\n').map(l => '        ' + l).join('\n')}
    }
}`;
}

/* ══════════════════════════════════════
   AUTH ROUTES
══════════════════════════════════════ */
app.post('/api/auth/register', async (req, res) => {
  try {
    const { name, username, email, password, photo } = req.body;
    if (!email || !password)
      return res.status(400).json({ error: 'Email and password are required.' });

    // SUPABASE (pg): use { rows } and $1 placeholders
    const { rows: existing } = await db.query(
      'SELECT id FROM users WHERE email = $1',
      [email]
    );
    if (existing.length > 0)
      return res.status(409).json({ error: 'An account with this email already exists.' });

    const hashed          = hashPassword(password);
    const displayName     = name     || email.split('@')[0];
    const displayUsername = username || email.split('@')[0];

    // SUPABASE (pg): use RETURNING id to get the inserted row's id
    const { rows: result } = await db.query(
      `INSERT INTO users (name, username, email, password_hash, photo)
       VALUES ($1, $2, $3, $4, $5) RETURNING id`,
      [displayName, displayUsername, email, hashed, photo || null]
    );

    res.status(201).json({
      success: true,
      user: {
        id:       result[0].id,
        name:     displayName,
        username: displayUsername,
        email,
        photo:    photo || null
      }
    });
  } catch (err) {
    console.error('❌ REGISTER:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password)
      return res.status(400).json({ error: 'Email and password are required.' });

    const hashed = hashPassword(password);

    // SUPABASE (pg): { rows } and $1, $2
    const { rows } = await db.query(
      `SELECT id, name, username, email, photo
       FROM users WHERE email = $1 AND password_hash = $2`,
      [email, hashed]
    );

    if (rows.length === 0)
      return res.status(401).json({ error: 'Invalid email or password.' });

    const user = rows[0];
    res.json({
      success: true,
      user: {
        id:       user.id,
        name:     user.name,
        username: user.username,
        email:    user.email,
        photo:    user.photo || null
      }
    });
  } catch (err) {
    console.error('❌ LOGIN:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/auth/google', async (req, res) => {
  try {
    const { name, email, photo } = req.body;
    if (!email) return res.status(400).json({ error: 'Google did not return an email.' });

    // SUPABASE (pg): { rows } and $1
    const { rows: existing } = await db.query(
      `SELECT id, name, username, email, photo FROM users WHERE email = $1`,
      [email]
    );

    if (existing.length > 0) {
      const user = existing[0];
      if (photo && photo !== user.photo) {
        await db.query('UPDATE users SET photo = $1 WHERE id = $2', [photo, user.id]);
        user.photo = photo;
      }
      return res.json({
        success: true,
        user: {
          id:       user.id,
          name:     user.name,
          username: user.username,
          email:    user.email,
          photo:    user.photo || null
        }
      });
    }

    const username = email.split('@')[0];

    // SUPABASE (pg): RETURNING to get new id
    const { rows: result } = await db.query(
      `INSERT INTO users (name, username, email, password_hash, photo)
       VALUES ($1, $2, $3, 'google-oauth', $4) RETURNING id`,
      [name || username, username, email, photo || null]
    );

    res.status(201).json({
      success: true,
      user: {
        id:       result[0].id,
        name:     name || username,
        username,
        email,
        photo:    photo || null
      }
    });
  } catch (err) {
    console.error('❌ GOOGLE AUTH:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.put('/api/auth/profile/:userId', async (req, res) => {
  try {
    const { userId } = req.params;
    const { name, username, email, password, photo } = req.body;
    const fields = [];
    const values = [];
    let   idx    = 1; // SUPABASE (pg): numbered placeholders start at $1

    if (name)                { fields.push(`name = $${idx++}`);          values.push(name); }
    if (username)            { fields.push(`username = $${idx++}`);      values.push(username); }
    if (email)               { fields.push(`email = $${idx++}`);         values.push(email); }
    if (photo !== undefined) { fields.push(`photo = $${idx++}`);         values.push(photo); }
    if (password && password !== '••••••••') {
      fields.push(`password_hash = $${idx++}`);
      values.push(hashPassword(password));
    }

    if (fields.length === 0) return res.status(400).json({ error: 'No fields to update.' });

    values.push(userId); // last param = userId
    await db.query(
      `UPDATE users SET ${fields.join(', ')} WHERE id = $${idx}`,
      values
    );

    // SUPABASE (pg): { rows } and $1
    const { rows } = await db.query(
      'SELECT id, name, username, email, photo FROM users WHERE id = $1',
      [userId]
    );
    res.json({ success: true, user: rows[0] });
  } catch (err) {
    console.error('❌ UPDATE PROFILE:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.delete('/api/auth/delete-account/:userId', async (req, res) => {
  try {
    const { userId } = req.params;

    if (!userId) {
      return res.status(400).json({ success: false, error: 'User ID is required.' });
    }

    console.log(`🗑️  Deleting account for user ${userId}...`);

    // Delete user_profiles first (child table)
    try {
      const profileResult = await db.query('DELETE FROM user_profiles WHERE user_id = $1', [userId]);
      console.log(`  → Deleted ${profileResult.rowCount || 0} profile rows`);
    } catch (profileErr) {
      console.warn(`  ⚠️  Error deleting profiles: ${profileErr.message}`);
      // Continue anyway; profiles might not exist
    }

    // Delete user account
    const userResult = await db.query('DELETE FROM users WHERE id = $1', [userId]);
    
    if (!userResult || userResult.rowCount === 0) {
      return res.status(404).json({ success: false, error: 'Account not found.' });
    }

    console.log(`✅ Account deleted for user ${userId}`);
    res.json({ success: true });
  } catch (err) {
    console.error('❌ DELETE ACCOUNT:', err.message, err.stack);
    res.status(500).json({ success: false, error: err.message });
  }
});

/* ══════════════════════════════════════
   API — GET PROBLEMS
══════════════════════════════════════ */
app.get('/api/problems/:language/:concept/:difficulty', async (req, res) => {
  try {
    const { language, concept, difficulty } = req.params;
    const tier = req.query.tier || 'Beginner';

    // SUPABASE (pg): { rows } and $1–$4
    const { rows } = await db.query(
      `SELECT * FROM problems
       WHERE language = $1 AND concept = $2 AND difficulty = $3 AND problem_tier = $4
       ORDER BY id ASC`,
      [language, concept, difficulty, tier]
    );

    if (rows.length === 0) {
      const fallbackProblems = getFallbackProblems({
        language,
        concept,
        difficulty,
        problemTier: tier
      });

      if (fallbackProblems.length > 0) {
        console.log(`⚠️ Using fallback problems for ${language}/${concept}/${difficulty}/${tier}`);
        return res.json(fallbackProblems);
      }
    }

    res.json(rows);
  } catch (err) {
    console.error('❌ GET PROBLEMS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — SUBMIT CODE
══════════════════════════════════════ */
app.post('/api/submit', async (req, res) => {
  try {
    const {
      userId, problemId, language, concept,
      code, attempts, timeSpent, isCorrect, hintUsed = false
    } = req.body;

    // ── 1. Fetch problem meta ────────────────────────────────────
    // SUPABASE (pg): { rows } and $1
    let problem = {};
    const { rows: problemRows } = await db.query(
      'SELECT * FROM problems WHERE id = $1',
      [problemId]
    );
    if (problemRows[0]) {
      problem = problemRows[0];
    } else {
      problem = resolveProblemMetadata(problemId) || {};
    }
    const requiredConstruct = problem.required_construct || null;
    const expectedOutput    = problem.expected_output    || '';

    // ── 2. CFG validation ────────────────────────────────────────
    const cfgResult        = validateCFG(code, language, requiredConstruct, expectedOutput);
    const syntaxErrors     = cfgResult.syntaxErrors;
    const structuralErrors = cfgResult.structuralErrors;
    const cfgFeedback      = cfgResult.feedback;
    const constructUsed    = cfgResult.constructUsed;

    // ── 3. Final correctness ─────────────────────────────────────
    const finalCorrect = isCorrect && constructUsed;
    const successValue = finalCorrect ? 1 : 0;

    // ── 4. Save submission ───────────────────────────────────────
    // SUPABASE (pg): $1–$11
    await db.query(
      `INSERT INTO submissions
       (user_id, problem_id, language, concept, submitted_code,
        attempts, time_spent, is_correct,
        syntax_errors, structural_errors, hint_used)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
      [
        userId,
        problemId,
        language,
        concept,
        code,
        attempts,
        timeSpent,
        finalCorrect,
        syntaxErrors,
        structuralErrors,
        hintUsed ? true : false  // pg uses true/false booleans (not 1/0)
      ]
    );

    // ── 5. Upsert user_profiles ──────────────────────────────────
    // SUPABASE (pg): { rows } and $1–$3
    const { rows: existing } = await db.query(
      `SELECT * FROM user_profiles WHERE user_id = $1 AND language = $2 AND concept = $3`,
      [userId, language, concept]
    );

    // Fetch real total task count for the concept.
    // user_profiles is scoped to language + concept, not difficulty.
    // SUPABASE (pg): COUNT(*) returns a string in pg — cast to int.
    const { rows: problemCountRows } = await db.query(
      `SELECT COUNT(*) AS total FROM problems WHERE language = $1 AND concept = $2`,
      [language, concept]
    );
    const totalTasksInDB = parseInt(problemCountRows[0]?.total, 10) || 3;

    // Determine whether this problem was already solved before this submission.
    const { rows: previousSolveRows } = await db.query(
      `SELECT COUNT(*) AS solved
       FROM submissions
       WHERE user_id = $1 AND problem_id = $2 AND is_correct = true`,
      [userId, problemId]
    );
    const alreadySolved = parseInt(previousSolveRows[0]?.solved, 10) > 0;
    const newlySolved = finalCorrect && !alreadySolved ? 1 : 0;

    // Preserve a learner's existing total_tasks once they have a profile.
    // This prevents the user's progress percentage from dropping if new
    // problems are added to the DB after they started the concept.
    const effectiveTotalTasks = existing.length > 0
      ? (existing[0].total_tasks || totalTasksInDB)
      : totalTasksInDB;

    if (existing.length === 0) {
      // SUPABASE (pg): $1–$10
      await db.query(
        `INSERT INTO user_profiles
         (user_id, language, concept, total_attempts, tasks_completed,
          total_tasks, success_rate, avg_time_spent, avg_attempts,
          syntax_errors, structural_errors, performance_level)
         VALUES ($1, $2, $3, 1, $4, $5, $6, $7, 1, $8, $9, 'Easy')`,
        [
          userId, language, concept,
          successValue, effectiveTotalTasks, successValue, timeSpent,
          syntaxErrors, structuralErrors
        ]
      );
    } else {
      // SUPABASE (pg): $1–$9
      await db.query(
        `UPDATE user_profiles SET
           total_attempts    = total_attempts + 1,
           tasks_completed   = tasks_completed + $1,
           total_tasks       = $2,
           success_rate      = (success_rate * total_attempts + $3) / (total_attempts + 1),
           avg_time_spent    = (avg_time_spent * total_attempts + $4) / (total_attempts + 1),
           avg_attempts      = (avg_attempts  * total_attempts + 1) / (total_attempts + 1),
           syntax_errors     = syntax_errors + $5,
           structural_errors = structural_errors + $6
         WHERE user_id = $7 AND language = $8 AND concept = $9`,
        [
          newlySolved, effectiveTotalTasks, successValue, timeSpent,
          syntaxErrors, structuralErrors,
          userId, language, concept
        ]
      );
    }

    // ── 6. CART classification ───────────────────────────────────
    // SUPABASE (pg): { rows } and $1–$3
    const { rows: profileRows } = await db.query(
      `SELECT success_rate, avg_time_spent, avg_attempts,
              syntax_errors, structural_errors, performance_level
       FROM user_profiles WHERE user_id = $1 AND language = $2 AND concept = $3`,
      [userId, language, concept]
    );

    const profile = profileRows[0] ?? {
      success_rate:      successValue,
      avg_time_spent:    timeSpent,
      avg_attempts:      attempts,
      syntax_errors:     syntaxErrors,
      structural_errors: structuralErrors,
      performance_level: 'Easy'
    };

    const { rows: conceptRows } = await db.query(
      `SELECT tasks_completed, total_tasks, success_rate
       FROM user_profiles
       WHERE user_id = $1 AND language = $2`,
      [userId, language]
    );

    let completionSum = 0;
    let weightedSuccess = 0;
    let totalTasks = 0;

    conceptRows.forEach(row => {
      const completed = Number(row.tasks_completed || 0);
      const total = Number(row.total_tasks || 0);
      const success = Number(row.success_rate || 0);
      const mastered = total > 0 && completed >= total && success >= 0.60;

      completionSum += mastered ? 1 : (total > 0 ? completed / total : 0);
      weightedSuccess += success * total;
      totalTasks += total;
    });

    const conceptCount = conceptRows.length;
    const completionRatio = conceptCount > 0 ? completionSum / conceptCount : 0;
    const successRate = totalTasks > 0 ? weightedSuccess / totalTasks : (conceptCount > 0 ? conceptRows.reduce((sum, row) => sum + Number(row.success_rate || 0), 0) / conceptCount : 0);
    const computedScore = Math.round((0.7 * completionRatio + 0.3 * successRate) * 100);

    // SUPABASE (pg): { rows } and $1–$3
    // pg returns COUNT as string — parse to int for comparison
    const { rows: hardSolveRows } = await db.query(
      `SELECT COUNT(*) AS count
       FROM submissions s
       JOIN problems p ON s.problem_id = p.id
       WHERE s.user_id = $1
         AND p.language = $2
         AND p.concept = $3
         AND p.problem_tier = 'Advanced'
         AND s.is_correct = true
         AND s.attempts <= 2
         AND s.hint_used = false`,
      [userId, language, concept]
    );
    const hasHardEvidence = parseInt(hardSolveRows[0].count, 10) > 0;

    // ── CART ML classification ────────────────────────────────────
    const featureVector = {
      success_rate:      profile.success_rate      ?? 0,
      avg_attempts:      profile.avg_attempts      ?? attempts,
      avg_time_spent:    profile.avg_time_spent     ?? timeSpent,
      syntax_errors:     profile.syntax_errors      ?? syntaxErrors,
      structural_errors: profile.structural_errors  ?? structuralErrors,
    };

    let level;
    if (cartReady) {
      level = cartModel.predict(featureVector);
      console.log(`🌳 CART predicted level="${level}" for user=${userId} concept=${concept}`);
    } else {
      if (
        featureVector.success_rate      >= 0.80 &&
        featureVector.avg_attempts      <= 2    &&
        featureVector.syntax_errors     <= 1    &&
        featureVector.structural_errors <= 1
      ) {
        level = 'Hard';
      } else if (featureVector.success_rate >= 0.50) {
        level = 'Intermediate';
      } else {
        level = 'Easy';
      }
      console.log(`⚠ CART fallback heuristic level="${level}" (model not loaded)`);
    }

    if (userId) {
      // SUPABASE (pg): $1–$4
      await db.query(
        `UPDATE user_profiles SET performance_level = $1
         WHERE user_id = $2 AND language = $3 AND concept = $4`,
        [level, userId, language, concept]
      );
    }

    let nextTier   = cartLevelToTier(level);
    let tierReason = null;

    if (nextTier === 'Advanced' && shouldDemote(profile, finalCorrect, attempts, hintUsed, hasHardEvidence)) {
      nextTier   = 'Intermediate';
      tierReason = 'We are giving you an Intermediate exercise to strengthen this concept before continuing with Advanced problems.';
    }

    if (nextTier === 'Intermediate' && shouldDemoteToEasy(profile, attempts, structuralErrors)) {
      nextTier   = 'Beginner';
      tierReason = 'We are revisiting the fundamentals of this concept to build a stronger foundation.';
    }

    // ── 7. Update daily_progress ─────────────────────────────────
    const today = new Date().toISOString().slice(0, 10);
    const score = computedScore;
    if (userId) {
      // SUPABASE (pg): ON CONFLICT replaces MySQL's ON DUPLICATE KEY UPDATE
      // Requires a UNIQUE constraint on (user_id, language, progress_date) in your schema
      await db.query(
        `INSERT INTO daily_progress (user_id, language, progress_date, score)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT (user_id, language, progress_date) DO UPDATE SET score =
           GREATEST(daily_progress.score, EXCLUDED.score)`,
        [userId, language, today, score]
      );
    }

    // ── 8. Cosine similarity recommendation ──────────────────────
    const updatedProfile = { ...profile, performance_level: level };

    // SUPABASE (pg): { rows } and $1
    const { rows: allProblems } = await db.query(
      `SELECT * FROM problems WHERE language = $1`,
      [language]
    );

    const { problem: recommended, similarityScore, explanation } =
      recommendExercise(updatedProfile, problem, allProblems);

    // ── 9. Save to recommendations table ─────────────────────────
    if (recommended && userId) {
      // SUPABASE (pg): { rows } and $1–$2
      const { rows: existingRec } = await db.query(
        `SELECT id FROM recommendations WHERE user_id = $1 AND source_problem_id = $2`,
        [userId, problemId]
      );

      if (existingRec.length === 0) {
        // SUPABASE (pg): NOW() works in both MySQL and PostgreSQL
        await db.query(
          `INSERT INTO recommendations
           (user_id, source_problem_id, recommended_problem_id,
            similarity_score, explanation, created_at)
           VALUES ($1, $2, $3, $4, $5, NOW())`,
          [userId, problemId, recommended.id, similarityScore, explanation]
        );
      } else {
        // SUPABASE (pg): $1–$5
        await db.query(
          `UPDATE recommendations SET
             recommended_problem_id = $1,
             similarity_score       = $2,
             explanation            = $3,
             created_at             = NOW()
           WHERE user_id = $4 AND source_problem_id = $5`,
          [recommended.id, similarityScore, explanation, userId, problemId]
        );
      }
    }

    // ── 10. Return full result ────────────────────────────────────
    // Check mastery: all tasks solved with ≥60% success
    const { rows: masterCheck } = await db.query(
      `SELECT tasks_completed, total_tasks, success_rate
       FROM user_profiles WHERE user_id = $1 AND language = $2 AND concept = $3`,
      [userId, language, concept]
    );
    const mr         = masterCheck[0];
    const isMastered = mr
      ? mr.tasks_completed >= mr.total_tasks && (mr.success_rate * 100) >= 60
      : false;

    res.json({
      success:         true,
      level,
      nextTier,
      correct:         finalCorrect,
      syntaxErrors,
      structuralErrors,
      cfgFeedback,
      constructUsed,
      isMastered,
      recommendation: recommended
        ? {
            id:              recommended.id,
            title:           recommended.title,
            concept:         recommended.concept,
            difficulty:      recommended.difficulty,
            problem_tier:    recommended.problem_tier,
            language:        recommended.language,
            similarityScore,
            explanation
          }
        : null
    });

  } catch (err) {
    console.error('❌ SUBMIT:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — GET RECOMMENDATIONS for a user
══════════════════════════════════════ */
app.get('/api/recommendations/:userId', async (req, res) => {
  try {
    const { userId } = req.params;

    // SUPABASE (pg): { rows } and $1
    const { rows } = await db.query(
      `SELECT
         r.id,
         r.similarity_score,
         r.explanation,
         r.created_at,
         sp.title        AS source_title,
         sp.concept      AS source_concept,
         sp.difficulty   AS source_difficulty,
         sp.problem_tier AS source_tier,
         rp.id           AS rec_problem_id,
         rp.title        AS rec_title,
         rp.concept      AS rec_concept,
         rp.difficulty   AS rec_difficulty,
         rp.problem_tier AS rec_tier,
         rp.language     AS rec_language,
         rp.instruction  AS rec_instruction
       FROM recommendations r
       JOIN problems sp ON r.source_problem_id      = sp.id
       JOIN problems rp ON r.recommended_problem_id = rp.id
       WHERE r.user_id = $1
       ORDER BY r.created_at DESC
       LIMIT 10`,
      [userId]
    );

    res.json(rows);
  } catch (err) {
    console.error('❌ GET RECOMMENDATIONS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — GET PROGRESS (for ProfilePage)
══════════════════════════════════════ */
app.get('/api/progress/:userId', async (req, res) => {
  try {
    const { userId } = req.params;

    // SUPABASE (pg): { rows } and $1
    const { rows } = await db.query(
      `SELECT language, concept, tasks_completed, total_tasks,
              success_rate, performance_level, syntax_errors, structural_errors
       FROM user_profiles WHERE user_id = $1`,
      [userId]
    );

    const progress = {};
    rows.forEach(row => {
      if (!progress[row.language]) progress[row.language] = {};
      const tasksCompleted = row.tasks_completed;
      const totalTasks     = row.total_tasks;
      const successRate    = Math.round(row.success_rate * 100);
      progress[row.language][row.concept] = {
        tasksCompleted,
        totalTasks,
        successRate,
        performanceLevel: row.performance_level,
        syntaxErrors:     row.syntax_errors,
        structuralErrors: row.structural_errors,
        mastered:         tasksCompleted >= totalTasks && successRate >= 60,
      };
    });
    res.json(progress);
  } catch (err) {
    console.error('❌ GET PROGRESS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/admin/users', async (req, res) => {
  try {
    // Get all users with overall stats
    const { rows: users } = await db.query(
      `SELECT
         u.id,
         u.name,
         u.username,
         u.email,
         u.photo,
         TO_CHAR(u.created_at, 'YYYY-MM-DD') AS joined_date,
         COALESCE(SUM(up.tasks_completed), 0) AS tasks_completed,
         COALESCE(SUM(up.total_tasks), 0) AS total_tasks,
         COALESCE(lp.progress, 0) AS progress,
         COALESCE(COUNT(DISTINCT up.concept), 0) AS concepts_count,
         COALESCE(dp.last_active, '') AS last_active
       FROM users u
       LEFT JOIN user_profiles up ON up.user_id = u.id
       LEFT JOIN LATERAL (
         SELECT GREATEST(
           COALESCE(
             (SELECT ROUND(AVG(concept_completion) * 100)
              FROM (
                SELECT
                  CASE
                    WHEN total_tasks > 0 AND tasks_completed > 0 AND success_rate >= 0.80
                         THEN 1
                    WHEN total_tasks > 0 AND tasks_completed > 0
                         THEN LEAST(success_rate, 1)
                    ELSE 0
                  END AS concept_completion
                FROM user_profiles
                WHERE user_id = u.id
              ) concept_progress),
             0
           ),
           COALESCE(
             (SELECT ROUND(AVG(best_score))
              FROM (
                SELECT language, MAX(score) AS best_score
                FROM daily_progress dp
                WHERE dp.user_id = u.id
                GROUP BY language
              ) best_scores),
             0
           )
         ) AS progress
       ) lp ON true
       LEFT JOIN LATERAL (
         SELECT TO_CHAR(MAX(progress_date), 'YYYY-MM-DD') AS last_active
         FROM daily_progress dp
         WHERE dp.user_id = u.id
       ) dp ON true
       GROUP BY u.id, u.created_at, dp.last_active, lp.progress
       ORDER BY u.name ASC`
    );

    // For each user, fetch per-language stats
    const enrichedUsers = await Promise.all(users.map(async (user) => {
      const { rows: langStats } = await db.query(
        `SELECT
           language,
           COALESCE(SUM(tasks_completed), 0) AS tasks_completed,
           COALESCE(SUM(total_tasks), 0) AS total_tasks,
           CASE WHEN COALESCE(SUM(total_tasks), 0) > 0
             THEN ROUND(AVG(success_rate) * 100)
             ELSE 0 END AS score
         FROM user_profiles
         WHERE user_id = $1
         GROUP BY language
         ORDER BY language ASC`,
        [user.id]
      );

      // Create score object for each language
      const scores = {
        python: 0,
        javascript: 0,
        java: 0
      };

      langStats.forEach(stat => {
        const lang = (stat.language || '').toLowerCase();
        if (lang === 'python') scores.python = Number(stat.score) || 0;
        else if (lang === 'javascript') scores.javascript = Number(stat.score) || 0;
        else if (lang === 'java') scores.java = Number(stat.score) || 0;
      });

      // Get language-specific progress details
      const { rows: langProgress } = await db.query(
        `SELECT
           language,
           COALESCE(SUM(tasks_completed), 0) AS tasks_completed,
           COALESCE(SUM(total_tasks), 0) AS total_tasks
         FROM user_profiles
         WHERE user_id = $1
         GROUP BY language
         ORDER BY language ASC`,
        [user.id]
      );

      const languageDetails = {};
      langProgress.forEach(lp => {
        const lang = (lp.language || '').toLowerCase();
        languageDetails[lang] = {
          tasksCompleted: Number(lp.tasks_completed) || 0,
          totalTasks: Number(lp.total_tasks) || 0
        };
      });

      return {
        id: user.id,
        name: user.name,
        username: user.username,
        email: user.email,
        photo: user.photo || null,
        progress: Number(user.progress),
        completedLessons: Number(user.tasks_completed),
        certificates: Number(user.concepts_count),
        enrolledDate: user.joined_date || 'Unknown',
        lastActive: user.last_active || 'Unknown',
        isBanned: false,
        scores,
        languageDetails
      };
    }));

    res.json(enrichedUsers);
  } catch (err) {
    console.error('❌ GET ADMIN USERS:', err.message);
    res.status(500).json({ error: err.message });
  }
});


app.get('/api/admin/content', async (req, res) => {
  try {
    const { rows: courseRows } = await db.query(
      `SELECT p.language,
              p.concept,
              COUNT(*) AS lessons,
              COUNT(DISTINCT up.user_id) AS enrolled
       FROM problems p
       LEFT JOIN user_profiles up
         ON up.language = p.language AND up.concept = p.concept
       GROUP BY p.language, p.concept
       ORDER BY lessons DESC, p.language ASC, p.concept ASC`
    );

    const courses = courseRows.map(row => ({
      id: `${row.language}-${row.concept}`,
      title: row.concept,
      language: row.language,
      lessons: Number(row.lessons),
      status: Number(row.enrolled) > 0 ? 'Active' : 'Draft',
      enrolled: Number(row.enrolled),
    }));

    const { rows: languageRows } = await db.query(
      `SELECT p.language,
              COUNT(DISTINCT p.concept) AS courses,
              COUNT(DISTINCT up.user_id) AS students
       FROM problems p
       LEFT JOIN user_profiles up
         ON up.language = p.language
       GROUP BY p.language
       ORDER BY p.language ASC`
    );

    const languages = languageRows.map(row => ({
      id: row.language,
      name: row.language,
      icon: row.language === 'Python' ? '🐍'
        : row.language === 'JavaScript' ? '📜'
        : row.language === 'Java' ? '☕'
        : '💻',
      color: row.language === 'Python' ? '#3776AB'
        : row.language === 'JavaScript' ? '#F7DF1E'
        : row.language === 'Java' ? '#007396'
        : '#5A67D8',
      courses: Number(row.courses),
      students: Number(row.students),
    }));

    res.json({ courses, languages });
  } catch (err) {
    console.error('❌ GET ADMIN CONTENT:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/admin/problems', async (req, res) => {
  try {
    const { rows } = await db.query(
      `SELECT id, title, language, concept, difficulty, problem_tier, instruction, expected_output, archived, created_at
       FROM problems
       ORDER BY created_at DESC`
    );

    res.json(rows);
  } catch (err) {
    console.error('❌ GET ADMIN PROBLEMS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/admin/problems', async (req, res) => {
  try {
    const {
      title,
      language,
      concept,
      difficulty,
      problem_tier,
      instruction,
      expected_output
    } = req.body;

    if (!title || !language || !concept || !difficulty || !problem_tier) {
      return res.status(400).json({ error: 'Missing required problem fields.' });
    }

    const { rows } = await db.query(
      `INSERT INTO problems
       (title, language, concept, difficulty, problem_tier, instruction, expected_output, created_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
       RETURNING id, title, language, concept, difficulty, problem_tier, instruction, expected_output, created_at`,
      [
        title,
        language,
        concept,
        difficulty,
        problem_tier,
        instruction || '',
        expected_output || ''
      ]
    );

    res.status(201).json(rows[0]);
  } catch (err) {
    console.error('❌ CREATE ADMIN PROBLEM:', err.message);
    res.status(500).json({ error: err.message });
  }
});

  app.put('/api/admin/problems/:id', async (req, res) => {
    try {
      const { id } = req.params;
      const {
        title,
        language,
        concept,
        difficulty,
        problem_tier,
        instruction,
        expected_output,
        archived
      } = req.body;

      if (!title || !language || !concept || !difficulty || !problem_tier) {
        return res.status(400).json({ error: 'Missing required problem fields.' });
      }

      const { rows } = await db.query(
        `UPDATE problems SET
           title = $1,
           language = $2,
           concept = $3,
           difficulty = $4,
           problem_tier = $5,
           instruction = $6,
           expected_output = $7,
           archived = COALESCE($8, archived)
         WHERE id = $9
         RETURNING id, title, language, concept, difficulty, problem_tier, instruction, expected_output, archived, created_at`,
        [
          title,
          language,
          concept,
          difficulty,
          problem_tier,
          instruction || '',
          expected_output || '',
          archived,
          id
        ]
      );

      if (!rows || rows.length === 0) return res.status(404).json({ error: 'Problem not found.' });
      res.json(rows[0]);
    } catch (err) {
      console.error('❌ UPDATE ADMIN PROBLEM:', err.message);
      res.status(500).json({ error: err.message });
    }
  });

app.patch('/api/admin/problems/:id/archive', async (req, res) => {
  try {
    const { id } = req.params;
    const { archived } = req.body;

    if (typeof archived !== 'boolean') {
      return res.status(400).json({ error: 'archived must be a boolean.' });
    }

    const { rows } = await db.query(
      `UPDATE problems SET archived = $1 WHERE id = $2 RETURNING id, title, language, concept, difficulty, problem_tier, instruction, expected_output, archived, created_at`,
      [archived, id]
    );

    if (!rows || rows.length === 0) {
      return res.status(404).json({ error: 'Problem not found.' });
    }

    res.json(rows[0]);
  } catch (err) {
    console.error('❌ PATCH ADMIN PROBLEM ARCHIVE:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.delete('/api/admin/problems/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const { rowCount } = await db.query(
      `DELETE FROM problems WHERE id = $1`,
      [id]
    );

    if (rowCount === 0) {
      return res.status(404).json({ error: 'Problem not found.' });
    }

    res.json({ success: true });
  } catch (err) {
    console.error('❌ DELETE ADMIN PROBLEM:', err.message);
    res.status(500).json({ error: err.message });
  }
});

const buildReportsUserSubquery = (timeframe, userType) => {
  const clauses = [];

  if (timeframe === '6m') {
    clauses.push(`EXISTS (SELECT 1 FROM daily_progress dp WHERE dp.user_id = u.id AND dp.progress_date >= CURRENT_DATE - INTERVAL '6 months')`);
  } else if (timeframe === '3m') {
    clauses.push(`EXISTS (SELECT 1 FROM daily_progress dp WHERE dp.user_id = u.id AND dp.progress_date >= CURRENT_DATE - INTERVAL '3 months')`);
  } else if (timeframe === '30d') {
    clauses.push(`EXISTS (SELECT 1 FROM daily_progress dp WHERE dp.user_id = u.id AND dp.progress_date >= CURRENT_DATE - INTERVAL '30 days')`);
  }

  if (userType === 'active') {
    clauses.push(`EXISTS (SELECT 1 FROM daily_progress dp WHERE dp.user_id = u.id AND dp.progress_date >= CURRENT_DATE - INTERVAL '30 days')`);
  }

  if (userType === 'new') {
    clauses.push(`u.created_at >= CURRENT_DATE - INTERVAL '30 days'`);
  }

  if (clauses.length === 0) {
    return null;
  }

  return `SELECT u.id FROM users u WHERE ${clauses.join(' AND ')}`;
};

const buildProfileWhereClause = (timeframe, userType) => {
  const clauses = [];
  const userSubquery = buildReportsUserSubquery(timeframe, userType);

  if (userSubquery) {
    clauses.push(`up.user_id IN (${userSubquery})`);
  }

  if (timeframe === '6m') {
    clauses.push(`up.last_updated >= CURRENT_DATE - INTERVAL '6 months'`);
  } else if (timeframe === '3m') {
    clauses.push(`up.last_updated >= CURRENT_DATE - INTERVAL '3 months'`);
  } else if (timeframe === '30d') {
    clauses.push(`up.last_updated >= CURRENT_DATE - INTERVAL '30 days'`);
  }

  return clauses.length ? `WHERE ${clauses.join(' AND ')}` : '';
};

const buildPerformanceWhere = (timeframe, userType) => {
  const clauses = [];

  if (timeframe === '6m') {
    clauses.push(`dp.progress_date >= CURRENT_DATE - INTERVAL '6 months'`);
  } else if (timeframe === '3m') {
    clauses.push(`dp.progress_date >= CURRENT_DATE - INTERVAL '3 months'`);
  } else if (timeframe === '30d') {
    clauses.push(`dp.progress_date >= CURRENT_DATE - INTERVAL '30 days'`);
  }

  if (userType === 'active') {
    clauses.push(`dp.progress_date >= CURRENT_DATE - INTERVAL '30 days'`);
  }

  if (userType === 'new') {
    clauses.push(`dp.user_id IN (SELECT id FROM users WHERE created_at >= CURRENT_DATE - INTERVAL '30 days')`);
  }

  return clauses.length ? `WHERE ${clauses.join(' AND ')}` : '';
};

app.get('/api/admin/reports', async (req, res) => {
  try {
    const selectedTimeframe = req.query.timeframe || 'all';
    const selectedUser = req.query.user || 'all';
    const profileWhere = buildProfileWhereClause(selectedTimeframe, selectedUser);
    const topicWhere = profileWhere.replace(/up\./g, '');
    const errorWhere = profileWhere.replace(/up\./g, '');
    const performanceWhere = buildPerformanceWhere(selectedTimeframe, selectedUser);

    const { rows: metricsRows } = await db.query(
      `WITH latest_scores AS (
         SELECT user_id, language, score
         FROM (
           SELECT user_id, language, score,
                  ROW_NUMBER() OVER (PARTITION BY user_id, language ORDER BY progress_date DESC) AS rn
           FROM daily_progress dp
           ${performanceWhere}
         ) ranked_scores
         WHERE rn = 1
       ), best_scores AS (
         SELECT user_id, language, MAX(score) AS best_score
         FROM daily_progress dp
         ${performanceWhere}
         GROUP BY user_id, language
       )
       SELECT
         (SELECT COALESCE(ROUND(AVG(score)), 0) FROM latest_scores) AS avg_score,
         (SELECT COALESCE(ROUND(AVG(best_score)), 0) FROM best_scores) AS avg_progress`
    );

    const { rows: performanceRows } = await db.query(
      `WITH months AS (
         SELECT generate_series(
           date_trunc('month', CURRENT_DATE) - INTERVAL '5 months',
           date_trunc('month', CURRENT_DATE),
           INTERVAL '1 month'
         ) AS month
       ), progress_by_month AS (
         SELECT date_trunc('month', progress_date) AS month,
                ROUND(AVG(score)) AS score,
                ROUND(AVG(score) * 0.95) AS success
         FROM daily_progress dp
         ${performanceWhere}
         GROUP BY 1
       )
       SELECT to_char(m.month, 'Mon ''YY') AS name,
              COALESCE(pb.score, 0) AS score,
              COALESCE(pb.success, 0) AS success
       FROM months m
       LEFT JOIN progress_by_month pb ON pb.month = m.month
       ORDER BY m.month ASC`
    );

    const { rows: topicRows } = await db.query(
      `SELECT concept AS name,
              COUNT(*) AS count
       FROM user_profiles up
       ${topicWhere}
       GROUP BY concept
       ORDER BY count DESC
       LIMIT 6`
    );

    const { rows: errorRows } = await db.query(
      `SELECT
         COALESCE(SUM(syntax_errors), 0) AS syntax_errors,
         COALESCE(SUM(structural_errors), 0) AS structural_errors
       FROM user_profiles up
       ${errorWhere}`
    );

    const metrics = metricsRows[0] || { avg_score: 0, avg_progress: 0 };
    const errorTotals = errorRows[0] || { syntax_errors: 0, structural_errors: 0 };

    const pieData = [
      { name: 'Syntax Errors', value: Number(errorTotals.syntax_errors), color: '#EE6666' },
      { name: 'Logic Errors', value: Number(errorTotals.structural_errors), color: '#FAC858' },
      { name: 'Other Errors', value: 0, color: '#5470C6' }
    ];

    res.json({
      avgScore: Number(metrics.avg_score),
      avgProgress: Number(metrics.avg_progress),
      performanceData: performanceRows.map(row => ({
        name: row.name,
        score: Number(row.score),
        success: Number(row.success),
      })),
      topics: topicRows.map((row, index) => ({
        name: row.name,
        count: Number(row.count),
        color: index % 2 === 0 ? '#76D7A4' : '#F1C40F'
      })),
      pieData,
    });
  } catch (err) {
    console.error('❌ GET ADMIN REPORTS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — DOWNLOAD RESEARCH DATA (Comprehensive CSV)
   GET /api/admin/reports/download
══════════════════════════════════════ */
app.get('/api/admin/reports/download', async (req, res) => {
  try {
    // Fetch all submissions with user and problem data
    let submissions = [];
    try {
      const { rows } = await db.query(
        `SELECT 
           s.id,
           u.name AS student_name,
           u.email AS student_email,
           p.title AS problem_title,
           p.language,
           p.concept,
           p.difficulty,
           p.problem_tier,
           s.attempts,
           s.time_spent,
           s.is_correct,
           s.syntax_errors,
           s.structural_errors,
           s.hint_used,
           TO_CHAR(s.created_at, 'YYYY-MM-DD HH24:MI:SS') AS submission_time
         FROM submissions s
         JOIN users u ON s.user_id = u.id
         JOIN problems p ON s.problem_id = p.id
         ORDER BY s.created_at DESC`
      );
      submissions = rows || [];
    } catch (err) {
      console.warn('⚠️ Submissions query warning:', err.message);
      submissions = [];
    }

    // Fetch user performance profiles
    let profiles = [];
    try {
      const { rows } = await db.query(
        `SELECT 
           up.user_id,
           u.name AS student_name,
           u.email AS student_email,
           up.language,
           up.concept,
           up.total_attempts,
           up.tasks_completed,
           up.total_tasks,
           ROUND(up.success_rate * 100, 2) AS success_rate_percent,
           ROUND(up.avg_time_spent, 2) AS avg_time_spent_sec,
           ROUND(up.avg_attempts::numeric, 2) AS avg_attempts,
           up.performance_level,
           up.syntax_errors,
           up.structural_errors
         FROM user_profiles up
         JOIN users u ON up.user_id = u.id
         ORDER BY u.name, up.language, up.concept`
      );
      profiles = rows || [];
    } catch (err) {
      console.warn('⚠️ Profiles query warning:', err.message);
      profiles = [];
    }

    // Fetch recommendations and effectiveness
    let recommendations = [];
    try {
      const { rows } = await db.query(
        `SELECT 
           r.user_id,
           u.name AS student_name,
           sp.title AS source_problem,
           sp.difficulty AS source_difficulty,
           sp.concept AS source_concept,
           rp.title AS recommended_problem,
           rp.difficulty AS recommended_difficulty,
           rp.concept AS recommended_concept,
           ROUND(r.similarity_score::numeric, 2) AS similarity_score,
           r.explanation,
           TO_CHAR(r.created_at, 'YYYY-MM-DD HH24:MI:SS') AS recommendation_time
         FROM recommendations r
         JOIN users u ON r.user_id = u.id
         JOIN problems sp ON r.source_problem_id = sp.id
         JOIN problems rp ON r.recommended_problem_id = rp.id
         ORDER BY r.created_at DESC`
      );
      recommendations = rows || [];
    } catch (err) {
      console.warn('⚠️ Recommendations query warning:', err.message);
      recommendations = [];
    }

    // Build report data
    const createdAt = new Date();
    const generatedAt = createdAt.toLocaleString();
    const uniqueStudents = new Set(submissions.map(s => s.student_email));
    const uniqueConcepts = new Set(profiles.map(p => p.concept));
    const uniqueLanguages = new Set(profiles.map(p => p.language));
    const correctSubmissions = submissions.filter(s => s.is_correct).length;
    const submissionSuccessRate = submissions.length > 0 ? ((correctSubmissions / submissions.length) * 100).toFixed(2) : '0.00';
    const avgSuccessRate = profiles.length > 0
      ? (profiles.reduce((sum, p) => sum + p.success_rate_percent, 0) / profiles.length).toFixed(2)
      : '0.00';

    let csvContent = 'Report Title, CodApt Research Data Export\n';
    csvContent += `Report Generated By, CodApt Learning Analytics\n`;
    csvContent += `Report Version, 1.0\n`;
    csvContent += `Generated At, ${generatedAt}\n`;
    csvContent += `Total Students, ${uniqueStudents.size}\n`;
    csvContent += `Total Submissions, ${submissions.length}\n`;
    csvContent += `Total Performance Profiles, ${profiles.length}\n`;
    csvContent += `Total Recommendations, ${recommendations.length}\n`;
    csvContent += `Unique Concepts, ${uniqueConcepts.size}\n`;
    csvContent += `Unique Languages, ${uniqueLanguages.size}\n\n`;

    csvContent += 'SUBMISSIONS DATA\n';
    csvContent += 'Student Name,Email,Problem Title,Language,Concept,Difficulty,Tier,Attempts,Time Spent (sec),Correct,Syntax Errors,Structural Errors,Hint Used,Submission Time\n';
    if (submissions.length === 0) {
      csvContent += 'No data available,,,,,,,,,,,,\n';
    } else {
      submissions.forEach(row => {
        const correctStr = row.is_correct ? 'Yes' : 'No';
        const hintStr = row.hint_used ? 'Yes' : 'No';
        csvContent += `"${row.student_name}","${row.student_email}","${row.problem_title}","${row.language}","${row.concept}","${row.difficulty}","${row.problem_tier}",${row.attempts},${row.time_spent},${correctStr},${row.syntax_errors},${row.structural_errors},${hintStr},"${row.submission_time}"\n`;
      });
    }

    csvContent += '\nSTUDENT PERFORMANCE PROFILES\n';
    csvContent += 'Student Name,Email,Language,Concept,Total Attempts,Tasks Completed,Total Tasks,Success Rate (%),Avg Time (sec),Avg Attempts,Performance Level,Syntax Errors,Structural Errors\n';
    if (profiles.length === 0) {
      csvContent += 'No data available,,,,,,,,,,,,\n';
    } else {
      profiles.forEach(row => {
        csvContent += `"${row.student_name}","${row.student_email}","${row.language}","${row.concept}",${row.total_attempts},${row.tasks_completed},${row.total_tasks},${row.success_rate_percent},${row.avg_time_spent_sec},${row.avg_attempts},"${row.performance_level}",${row.syntax_errors},${row.structural_errors}\n`;
      });
    }

    csvContent += '\nRECOMMENDATIONS & EFFECTIVENESS\n';
    csvContent += 'Student Name,Source Problem,Source Difficulty,Source Concept,Recommended Problem,Recommended Difficulty,Recommended Concept,Similarity Score,Explanation,Recommendation Time\n';
    if (recommendations.length === 0) {
      csvContent += 'No data available,,,,,,,,,,,\n';
    } else {
      recommendations.forEach(row => {
        const safeExplanation = (row.explanation || '').replace(/"/g, '""');
        csvContent += `"${row.student_name}","${row.source_problem}","${row.source_difficulty}","${row.source_concept}","${row.recommended_problem}","${row.recommended_difficulty}","${row.recommended_concept}",${row.similarity_score},"${safeExplanation}","${row.recommendation_time}"\n`;
      });
    }

    csvContent += '\nSUMMARY STATISTICS\n';
    csvContent += `Metric,Value\n`;
    csvContent += `Correct Submissions,${correctSubmissions}\n`;
    csvContent += `Submission Success Rate (%),${submissionSuccessRate}\n`;
    csvContent += `Average Student Success Rate (%),${avgSuccessRate}\n`;
    csvContent += `Unique Concepts,${uniqueConcepts.size}\n`;
    csvContent += `Unique Languages,${uniqueLanguages.size}\n`;
    csvContent += `Report Notes,This export includes raw submissions, student profiles, recommendation results, and summary metrics for research reporting.\n`;
    csvContent += `Generated By,CodApt Thesis Export Module\n`;
    csvContent += `Export Format,CSV\n`;

    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="CodApt_Research_Report_${createdAt.getFullYear()}${(createdAt.getMonth()+1).toString().padStart(2,'0')}${createdAt.getDate().toString().padStart(2,'0')}_${createdAt.getHours().toString().padStart(2,'0')}${createdAt.getMinutes().toString().padStart(2,'0')}${createdAt.getSeconds().toString().padStart(2,'0')}.csv"`);
    res.send(csvContent);
  } catch (err) {
    console.error('❌ DOWNLOAD RESEARCH DATA:', err.message);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/admin/reset-experiment-data', async (req, res) => {
  try {
    const { rowCount: deletedSubmissions } = await db.query('DELETE FROM submissions');
    const { rowCount: deletedProfiles } = await db.query('DELETE FROM user_profiles');
    const { rowCount: deletedProgress } = await db.query('DELETE FROM daily_progress');
    const { rowCount: deletedRecommendations } = await db.query('DELETE FROM recommendations');

    res.json({
      success: true,
      deletedSubmissions,
      deletedProfiles,
      deletedProgress,
      deletedRecommendations
    });
  } catch (err) {
    console.error('❌ RESET EXPERIMENT DATA:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — GET DAILY PROGRESS
══════════════════════════════════════ */
app.get('/api/daily-progress/:userId', async (req, res) => {
  try {
    const { userId } = req.params;

    // Return a broader history window so the profile chart reflects the
    // learner's progression over time instead of dropping to a fallback
    // two-point line when older entries are outside a short window.
    const { rows } = await db.query(
      `SELECT progress_date, language, score
       FROM daily_progress
       WHERE user_id = $1
         AND progress_date >= CURRENT_DATE - INTERVAL '365 days'
       ORDER BY progress_date ASC, language ASC`,
      [userId]
    );

    res.json(rows);
  } catch (err) {
    console.error('❌ GET DAILY PROGRESS:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   API — RETRAIN CART MODEL
   POST /api/retrain
══════════════════════════════════════ */
app.post('/api/retrain', async (req, res) => {
  const scriptPath = path.join(__dirname, 'utils', 'trainCart.js');

  if (!fs.existsSync(scriptPath)) {
    return res.status(500).json({ error: `Training script not found at ${scriptPath}` });
  }

  exec(`node "${scriptPath}"`, { timeout: 60000 }, (err, stdout, stderr) => {
    if (err) {
      console.error('❌ Retrain failed:', stderr || err.message);
      return res.status(500).json({ error: 'Training failed', details: stderr || err.message });
    }

    try {
      const exported = JSON.parse(fs.readFileSync(CART_MODEL_PATH, 'utf8'));
      cartModel.importTree(exported);
      cartReady = true;
      console.log('✅ CART model reloaded after retraining.');
      res.json({
        success:    true,
        trained_at: exported.meta.trained_at,
        features:   exported.meta.features,
        max_depth:  exported.meta.max_depth,
        output:     stdout,
      });
    } catch (loadErr) {
      res.status(500).json({ error: 'Model trained but failed to reload', details: loadErr.message });
    }
  });
});

/* ══════════════════════════════════════
   API — INSPECT CART MODEL
   GET /api/cart-model
══════════════════════════════════════ */
app.get('/api/cart-model', (req, res) => {
  if (!cartReady) {
    return res.status(503).json({
      ready:   false,
      message: 'CART model not loaded. Run: node utils/trainCart.js',
    });
  }
  res.json({ ready: true, ...cartModel.exportTree() });
});

/* ══════════════════════════════════════
   API — CONNECTION TEST
══════════════════════════════════════ */
app.get('/api/test', async (req, res) => {
  try {
    // SUPABASE (pg): { rows } — COUNT(*) returns string, cast to int
    const { rows } = await db.query('SELECT COUNT(*) AS total FROM problems');
    res.json({ status: 'connected', problems: parseInt(rows[0].total, 10) });
  } catch (err) {
    res.status(500).json({ status: 'error', message: err.message });
  }
});

/* ══════════════════════════════════════
   ADMIN PROFILE — SAVE
   PUT /api/admin/profile
══════════════════════════════════════ */
app.put('/api/admin/profile', async (req, res) => {
  try {
    const { name, username, email } = req.body;
    
    if (!name || !username || !email) {
      return res.status(400).json({ error: 'Name, username, and email are required.' });
    }

    // For this simple admin profile, we'll store in a settings table
    // First, check if admin profile exists
    const { rows: existing } = await db.query(
      'SELECT * FROM admin_settings WHERE admin_id = 1'
    );

    if (existing.length > 0) {
      // Update existing
      const { rows } = await db.query(
        'UPDATE admin_settings SET name = $1, username = $2, email = $3, updated_at = NOW() WHERE admin_id = 1 RETURNING *',
        [name, username, email]
      );
      res.json({ success: true, admin: rows[0] });
    } else {
      // Create new
      const { rows } = await db.query(
        'INSERT INTO admin_settings (admin_id, name, username, email, created_at, updated_at) VALUES (1, $1, $2, $3, NOW(), NOW()) RETURNING *',
        [name, username, email]
      );
      res.json({ success: true, admin: rows[0] });
    }
  } catch (err) {
    console.error('❌ SAVE ADMIN PROFILE:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   ADMIN PROFILE — GET
   GET /api/admin/profile
══════════════════════════════════════ */
app.get('/api/admin/profile', async (req, res) => {
  try {
    const { rows } = await db.query(
      'SELECT * FROM admin_settings WHERE admin_id = 1'
    );
    if (rows.length === 0) {
      return res.json({ admin: { name: 'Admin', username: 'admin', email: '' } });
    }
    res.json({ admin: rows[0] });
  } catch (err) {
    console.error('❌ GET ADMIN PROFILE:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/* ══════════════════════════════════════
   START SERVER
══════════════════════════════════════ */
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Backend running at http://localhost:${PORT}`));